// AUTO-GENERATED by tauri-specta — do not edit by hand.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	// `true` if the registry currently has at least one hot profile.
	vaultExists: () => typedError<boolean, CmdError>(__TAURI_INVOKE("vault_exists")),
	createWallet: (args: CreateWalletArgs) => typedError<string, CmdError>(__TAURI_INVOKE("create_wallet", { args })),
	importWallet: (args: ImportWalletArgs) => typedError<null, CmdError>(__TAURI_INVOKE("import_wallet", { args })),
	unlockWallet: (password: string) => typedError<null, CmdError>(__TAURI_INVOKE("unlock_wallet", { password })),
	lockWallet: () => typedError<null, CmdError>(__TAURI_INVOKE("lock_wallet")),
	isUnlocked: () => typedError<boolean, CmdError>(__TAURI_INVOKE("is_unlocked")),
	listChains: () => typedError<ChainSummary[], CmdError>(__TAURI_INVOKE("list_chains")),
	listTokens: () => typedError<TokenSummary[], CmdError>(__TAURI_INVOKE("list_tokens")),
	/**
	 *  Curated token-list URLs Atlas ships with by default. The frontend
	 *  uses this to populate the "Refresh from tokenlists.org" picker.
	 */
	tokenListDefaultUrls: () => typedError<string[], CmdError>(__TAURI_INVOKE("token_list_default_urls")),
	/**
	 *  Fetch a Uniswap-format token list from `url` and return the parsed
	 *  tokens for any chain Atlas supports. Network errors and invalid JSON
	 *  surface as [`CmdError::InvalidInput`].
	 */
	tokenListFetch: (url: string) => typedError<OwnedTokenMeta[], CmdError>(__TAURI_INVOKE("token_list_fetch", { url })),
	/**
	 *  Add a custom user-imported token. Validates contract format (`0x` +
	 *  40 hex chars for EVM, base58 for Tron) before persisting so the UI
	 *  can't poison the local DB with garbage.
	 */
	tokenAddCustom: (chainId: string, contract: string, symbol: string, displayName: string, decimals: number, logoUri: string | null) => typedError<null, CmdError>(__TAURI_INVOKE("token_add_custom", { chainId, contract, symbol, displayName, decimals, logoUri })),
	// List custom tokens for `chain_id` (or all chains when empty).
	tokenListCustom: (chainId: string) => typedError<CustomToken[], CmdError>(__TAURI_INVOKE("token_list_custom", { chainId })),
	// Remove one custom token. Returns `true` if a row was deleted.
	tokenRemoveCustom: (chainId: string, contract: string) => typedError<boolean, CmdError>(__TAURI_INVOKE("token_remove_custom", { chainId, contract })),
	// List every supported chain id alongside its default and (if any) overridden RPC.
	listRpcEndpoints: () => typedError<RpcEndpoint[], CmdError>(__TAURI_INVOKE("list_rpc_endpoints")),
	/**
	 *  Override the RPC URL for a given chain. The new endpoint takes effect
	 *  immediately for every subsequent IPC call.
	 */
	setRpcEndpoint: (chainId: string, url: string) => typedError<RpcEndpoint, CmdError>(__TAURI_INVOKE("set_rpc_endpoint", { chainId, url })),
	// Remove the user override for a chain, falling back to the built-in default.
	clearRpcEndpoint: (chainId: string) => typedError<RpcEndpoint, CmdError>(__TAURI_INVOKE("clear_rpc_endpoint", { chainId })),
	getAddress: (chainId: string) => typedError<string, CmdError>(__TAURI_INVOKE("get_address", { chainId })),
	getBalance: (chainId: string) => typedError<Amount, CmdError>(__TAURI_INVOKE("get_balance", { chainId })),
	getFeeOptions: (chainId: string) => typedError<FeeOption[], CmdError>(__TAURI_INVOKE("get_fee_options", { chainId })),
	sendNative: (args: SendNativeArgs) => typedError<SendNativeResult, CmdError>(__TAURI_INVOKE("send_native", { args })),
	// Sign and broadcast a token transfer (ERC-20 or TRC-20).
	sendToken: (args: SendTokenArgs) => typedError<SendTokenResult, CmdError>(__TAURI_INVOKE("send_token", { args })),
	getPrices: (ids: string[], currency: string | null) => typedError<{ [key in string]: PricePoint }, CmdError>(__TAURI_INVOKE("get_prices", { ids, currency })),
	// Currently persisted display currency (`"usd"` / `"eur"` / `"gbp"`).
	getFiatCurrency: () => typedError<string, CmdError>(__TAURI_INVOKE("get_fiat_currency")),
	// Persist a new display currency. Accepts `"usd"`, `"eur"`, or `"gbp"`.
	setFiatCurrency: (currency: string) => typedError<string, CmdError>(__TAURI_INVOKE("set_fiat_currency", { currency })),
	// Currently configured auto-lock timeout (minutes). `0` means disabled.
	getAutoLockMinutes: () => typedError<number, CmdError>(__TAURI_INVOKE("get_auto_lock_minutes")),
	/**
	 *  Persist a new auto-lock timeout. `0` disables auto-lock entirely.
	 *  Values above 1440 (24h) are clamped to discourage forever-unlocked sessions.
	 */
	setAutoLockMinutes: (minutes: number) => typedError<number, CmdError>(__TAURI_INVOKE("set_auto_lock_minutes", { minutes })),
	// Probe a single chain's effective endpoint and return latency / status.
	networkHealth: (chainId: string) => typedError<NetworkHealth, CmdError>(__TAURI_INVOKE("network_health", { chainId })),
	// Probe every supported chain in parallel.
	networkHealthAll: () => typedError<NetworkHealth[], CmdError>(__TAURI_INVOKE("network_health_all")),
	// Inspect (without revealing) the user's 1inch configuration.
	getExchangeSettings: () => typedError<ExchangeSettings, CmdError>(__TAURI_INVOKE("get_exchange_settings")),
	// Persist 1inch credentials. Pass `null` (or empty) to clear a field.
	setExchangeSettings: (args: ExchangeConfigArgs) => typedError<ExchangeSettings, CmdError>(__TAURI_INVOKE("set_exchange_settings", { args })),
	/**
	 *  Quote an EVM swap via 1inch v6.
	 * 
	 *  `chain_id` is the EIP-155 chain id (1 = mainnet, 137 = polygon, …).
	 *  Token addresses use 1inch's convention: the native asset is
	 *  `0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee`.
	 */
	exchangeQuote: (chainId: number, src: string, dst: string, amount: string) => typedError<Quote, CmdError>(__TAURI_INVOKE("exchange_quote", { chainId, src, dst, amount })),
	/**
	 *  Execute an EVM swap via 1inch v6.
	 * 
	 *  For ERC-20 source tokens this command also handles the on-chain
	 *  allowance: if the router's allowance is below the requested amount,
	 *  Atlas signs and broadcasts an `approve` transaction first, then the
	 *  swap. Both transactions use the wallet's pending nonce — the swap is
	 *  expected to land in the block immediately after the approval.
	 */
	exchangeSwap: (args: ExchangeSwapArgs) => typedError<ExchangeSwapResult, CmdError>(__TAURI_INVOKE("exchange_swap", { args })),
	listProfiles: () => typedError<ProfileSummary[], CmdError>(__TAURI_INVOKE("list_profiles")),
	activeProfile: () => typedError<{
	// Stable id (as string for JS).
	id: string,
	// Human-visible label.
	name: string,
	// `"hot"` or `"watch_only"`.
	kind: string,
	// Whether this profile can sign transactions.
	signing: boolean,
	// Creation timestamp.
	created_at: string,
	// Number of watched accounts (0 for hot profiles).
	watch_account_count: number,
} | null, CmdError>(__TAURI_INVOKE("active_profile")),
	switchProfile: (id: string) => typedError<null, CmdError>(__TAURI_INVOKE("switch_profile", { id })),
	renameProfile: (id: string, newName: string) => typedError<null, CmdError>(__TAURI_INVOKE("rename_profile", { id, newName })),
	deleteProfile: (id: string) => typedError<null, CmdError>(__TAURI_INVOKE("delete_profile", { id })),
	createWatchOnlyProfile: (args: CreateWatchOnlyArgs) => typedError<ProfileSummary, CmdError>(__TAURI_INVOKE("create_watch_only_profile", { args })),
	/**
	 *  Return the most-recent cached transactions. Pass chain_id = "" to query
	 *  across every chain.
	 */
	txHistoryList: (chainId: string, limit: number) => typedError<TxRecord[], CmdError>(__TAURI_INVOKE("tx_history_list", { chainId, limit })),
	/**
	 *  Update the on-disk status of a single tx (pending ? confirmed/failed).
	 *  The frontend can call this once a confirmation watcher resolves.
	 */
	txHistorySetStatus: (chainId: string, txid: string, status: string) => typedError<null, CmdError>(__TAURI_INVOKE("tx_history_set_status", { chainId, txid, status })),
	/**
	 *  Allow the UI to record a tx that didn't go through Atlas's send flow
	 *  (e.g. an external broadcast the user wants to track).
	 */
	txHistoryRecord: (record: TxRecord) => typedError<null, CmdError>(__TAURI_INVOKE("tx_history_record", { record })),
	/**
	 *  Add (or replace) an encrypted address-book entry. Requires the
	 *  wallet to be unlocked because the encryption key is derived from
	 *  the BIP-39 seed.
	 */
	addressBookPut: (chainId: string, address: string, label: string, notes: string | null) => typedError<null, CmdError>(__TAURI_INVOKE("address_book_put", { chainId, address, label, notes })),
	/**
	 *  List address-book entries (decrypted) for `chain_id`. Pass an empty
	 *  string to list across every chain. Requires the wallet to be
	 *  unlocked.
	 */
	addressBookList: (chainId: string) => typedError<AddressBookEntry[], CmdError>(__TAURI_INVOKE("address_book_list", { chainId })),
	/**
	 *  Remove one address-book entry. Returns `true` if a row was deleted.
	 *  Does NOT require the wallet to be unlocked — the row identifiers
	 *  (chain_id, address) are stored as plaintext.
	 */
	addressBookRemove: (chainId: string, address: string) => typedError<boolean, CmdError>(__TAURI_INVOKE("address_book_remove", { chainId, address })),
};

/** Events */
export const events = {
	balanceUpdatedEvent: makeEvent<BalanceUpdatedEvent>("balance-updated-event"),
	txRecordedEvent: makeEvent<TxRecordedEvent>("tx-recorded-event"),
	txStatusChangedEvent: makeEvent<TxStatusChangedEvent>("tx-status-changed-event"),
	walletLockedEvent: makeEvent<WalletLockedEvent>("wallet-locked-event"),
};

/* Types */
// One decrypted address-book entry as the UI sees it.
export type AddressBookEntry = {
	// Atlas chain id (`"eth"`, `"btc"`, …).
	chain_id: string,
	// Public address (plaintext).
	address: string,
	// User-supplied display label (decrypted).
	label: string,
	// Optional notes (decrypted).
	notes: string | null,
	// Unix timestamp (seconds) when the entry was added.
	created_at: number,
};

/**
 *  A precise on-chain amount: integer base units + asset metadata.
 * 
 *  `value` is denominated in the asset's smallest unit (sat for BTC,
 *  wei for ETH). We use `u128` as a JSON-friendly carrier for any
 *  realistic balance.
 */
export type Amount = {
	// Integer value in base units.
	value: number,
	// Asset this amount denominates.
	asset: Asset,
};

// A cryptocurrency asset (native or token).
export type Asset = {
	// Stable identifier — usually the lowercase ticker (`btc`, `eth`, `usdc`).
	id: string,
	// Display ticker, e.g. `BTC`.
	symbol: string,
	// Decimals (8 for BTC, 18 for ETH, 6 for USDC, …).
	decimals: number,
	// Optional logo URL/hint for the UI.
	logo: string | null,
};

/**
 *  Emitted when a balance refresh observes a different value than what the
 *  frontend last queried. Reserved for the upcoming background watcher —
 *  kept in the schema now so listening UI code is forward-compatible.
 */
export type BalanceUpdatedEvent = {
	chain_id: string,
	address: string,
	// Base-units integer encoded as a decimal string for u128 safety.
	amount: string,
	asset: string,
};

export type ChainSummary = {
	id: string,
	display_name: string,
	symbol: string,
	decimals: number,
	family: string,
	enabled_by_default: boolean,
};

export type CmdError = { kind: "NotInitialized"; message: string } | { kind: "Locked" } | { kind: "InvalidInput"; message: string } | { kind: "Wallet"; message: string } | { kind: "Chain"; message: string } | { kind: "Io"; message: string } | { kind: "Profile"; message: string };

export type CreateWalletArgs = {
	password: string,
	word_count: number,
	/**
	 *  Optional human-friendly profile name. Defaults to `"Default"` for the
	 *  first wallet, otherwise required.
	 */
	name?: string | null,
};

export type CreateWatchOnlyArgs = {
	name: string,
	accounts: WatchAccount[],
};

/**
 *  One user-imported token row. Mirrors `OwnedTokenMeta` minus the
 *  derived `id` / `source` (which are always `"custom"` here).
 */
export type CustomToken = {
	// Atlas chain id (`"eth"`, `"polygon"`, …).
	chain_id: string,
	/**
	 *  Contract address (case-preserved as the user typed it; lookups
	 *  should compare case-insensitively).
	 */
	contract: string,
	// On-chain ticker.
	symbol: string,
	// Display name.
	display_name: string,
	// Decimals (0–38).
	decimals: number,
	// `"erc-20"` or `"trc-20"`.
	standard: string,
	// Optional logo URL.
	logo_uri: string | null,
};

export type ExchangeConfigArgs = {
	api_key: string | null,
	base_url: string | null,
};

export type ExchangeSettings = {
	api_key_set: boolean,
	base_url: string,
};

export type ExchangeSwapArgs = {
	chain_id: number,
	src: string,
	dst: string,
	// Source amount, base units, decimal string.
	amount: string,
	// Maximum slippage in basis points (100 = 1%).
	slippage_bps: number,
	// `slow|normal|fast` or a raw decimal wei gas-price.
	fee_level: string,
};

export type ExchangeSwapResult = {
	// Final swap transaction hash.
	txid: string,
	// If a pre-approve was needed (ERC-20 source), this is its tx hash.
	approve_txid: string | null,
	// Estimated destination amount, base units, decimal string.
	to_amount: string,
};

// Three canonical fee tiers presented to the user.
export type FeeOption = {
	// `"slow" | "normal" | "fast"`.
	level: string,
	// Estimated fee for a typical transaction.
	estimated_fee: Amount,
	// Estimated time-to-confirm in seconds.
	eta_seconds: number,
	// Implementation-defined hint payload (e.g. sat/vB or gas price), JSON-encoded as string for FFI simplicity.
	raw_hint: string,
};

export type ImportWalletArgs = {
	password: string,
	phrase: string,
	passphrase?: string | null,
	name?: string | null,
};

// Result of a single `network_health` probe.
export type NetworkHealth = {
	// Chain id this report describes (`"btc"`, `"eth"`, …).
	chain_id: string,
	// Effective endpoint URL we probed.
	endpoint: string,
	// Whether the endpoint URL is the user's override (`true`) or built-in default.
	is_user_override: boolean,
	// Number of samples sent.
	samples: number,
	// Number of samples that returned successfully.
	successes: number,
	// Median latency across successful samples, in milliseconds.
	latency_p50_ms: number | null,
	// 95th percentile latency across successful samples, in milliseconds.
	latency_p95_ms: number | null,
	// Most recently observed head height (block / slot number).
	head_height: number | null,
	// Bucketed status for the UI.
	status: NetworkStatus,
};

// Per-chain status bucket surfaced to the UI as a green / amber / red dot.
export type NetworkStatus = 
// Endpoint is reachable and responsive.
"synced" | 
// Endpoint responds but is slow or losing samples.
"lagging" | 
// All samples failed.
"offline";

/**
 *  Owned counterpart of [`TokenMeta`] used for tokens fetched at runtime
 *  from tokenlists.org or imported manually by the user.
 * 
 *  Static + remote tokens unify behind this type at the IPC boundary so
 *  the UI can display both kinds without caring where they came from.
 */
export type OwnedTokenMeta = {
	/**
	 *  Stable identifier — for remote tokens this is `chain_id-contract`
	 *  in lowercase so duplicates dedupe naturally.
	 */
	id: string,
	// On-chain symbol.
	symbol: string,
	// Display name.
	display_name: string,
	// Atlas chain id (`"eth"`, `"polygon"`, …).
	chain_id: string,
	// Hex (EIP-55) or base58 contract address.
	contract: string,
	// On-chain decimals.
	decimals: number,
	// Token standard.
	standard: TokenStandard,
	// Optional logo URL (only present on remote tokens).
	logo_uri: string | null,
	// `"static"`, `"remote"` (tokenlists.org), or `"custom"` (user-added).
	source: string,
};

// A single cached price observation.
export type PricePoint = {
	// Price in the requested fiat currency.
	price: number,
	// 24h change as a percentage.
	change_24h: number,
};

// Frontend-friendly summary of a profile.
export type ProfileSummary = {
	// Stable id (as string for JS).
	id: string,
	// Human-visible label.
	name: string,
	// `"hot"` or `"watch_only"`.
	kind: string,
	// Whether this profile can sign transactions.
	signing: boolean,
	// Creation timestamp.
	created_at: string,
	// Number of watched accounts (0 for hot profiles).
	watch_account_count: number,
};

// 1inch v6 quote response, lifted into a stable shape.
export type Quote = {
	// Source token address (lowercase 0x…).
	from_token: string,
	// Destination token address.
	to_token: string,
	// Source amount, base units, decimal string.
	from_amount: string,
	// Estimated destination amount, base units, decimal string.
	to_amount: string,
	// Estimated gas units for the swap (advisory).
	estimated_gas: number,
	// Optional names of protocols routed through.
	protocols: string[],
};

export type RpcEndpoint = {
	chain_id: string,
	// Built-in default URL Atlas falls back to when no override is set.
	default_url: string | null,
	// User-configured override, if any.
	override_url: string | null,
	// The URL providers are actually dialing right now.
	effective_url: string | null,
};

export type SendNativeArgs = {
	chain_id: string,
	to: string,
	amount: string,
	fee_level: string,
};

export type SendNativeResult = {
	txid: string,
	fee: Amount,
};

export type SendTokenArgs = {
	// Token id from the registry (e.g. `usdt-erc20`).
	token_id: string,
	to: string,
	// Token amount in base units (string-encoded u128).
	amount: string,
	fee_level: string,
};

export type SendTokenResult = {
	txid: string,
	// Network fee paid in the chain's native asset.
	fee: Amount,
};

// Token contract standard.
export type TokenStandard = 
// Ethereum / EVM-compatible ERC-20 contract.
"erc20" | 
// Tron TRC-20 contract.
"trc20";

export type TokenSummary = {
	id: string,
	symbol: string,
	display_name: string,
	chain_id: string,
	contract: string,
	decimals: number,
	standard: string,
	enabled_by_default: boolean,
};

// One on-chain transaction the user (or Atlas itself) initiated.
export type TxRecord = {
	// Transaction id / hash, lower-case hex (no `0x` for BTC; with `0x` for EVM).
	txid: string,
	// Chain id (`"btc"`, `"eth"`, `"sol"`, …).
	chain_id: string,
	/**
	 *  `"send"` or `"receive"`. Atlas only writes `"send"` itself today;
	 *  `"receive"` rows are reserved for future explorer-driven enrichment.
	 */
	direction: string,
	// Other party's address.
	counterparty: string,
	// Amount in base units, decimal-string (u128-friendly).
	amount: string,
	// Asset ticker (`"BTC"`, `"ETH"`, `"USDT"`, …).
	asset: string,
	// Network fee paid, decimal string in the chain's native asset base units.
	fee: string,
	// Unix timestamp (seconds) when the tx was broadcast.
	timestamp: number,
	// `"pending"`, `"confirmed"`, or `"failed"`.
	status: string,
	// Optional user-supplied note.
	memo: string | null,
};

/**
 *  Emitted right after a tx is appended to the local cache (whether Atlas
 *  signed it or the UI explicitly recorded an external one). The TX list
 *  view subscribes and updates in place.
 */
export type TxRecordedEvent = {
	record: TxRecord,
};

/**
 *  Emitted when [`crate::commands::tx_history_set_status`] flips a row's
 *  status field (e.g. pending → confirmed once a watcher resolves).
 */
export type TxStatusChangedEvent = {
	chain_id: string,
	txid: string,
	status: string,
};

/**
 *  Emitted when the wallet transitions from unlocked to locked, regardless
 *  of cause (manual, idle timeout, profile switch, …). The frontend uses
 *  this to evict in-memory state and route to `/unlock`.
 */
export type WalletLockedEvent = {
	// `"manual"`, `"idle"`, `"profile_switch"`, or `"shutdown"`.
	reason: string,
};

// A `(chain_id, address)` pair tracked by a watch-only profile.
export type WatchAccount = {
	// Chain identifier (e.g. `"btc"`, `"eth"`, `"polygon"`).
	chain_id: string,
	// Public address (no private key material).
	address: string,
	// Optional human label.
	label?: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

