// AUTO-GENERATED by tauri-specta — do not edit by hand.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	// `true` if the registry currently has at least one hot profile.
	vaultExists: () => typedError<boolean, CmdError>(__TAURI_INVOKE("vault_exists")),
	createWallet: (args: CreateWalletArgs) => typedError<string, CmdError>(__TAURI_INVOKE("create_wallet", { args })),
	importWallet: (args: ImportWalletArgs) => typedError<null, CmdError>(__TAURI_INVOKE("import_wallet", { args })),
	unlockWallet: (password: string) => typedError<null, CmdError>(__TAURI_INVOKE("unlock_wallet", { password })),
	lockWallet: () => typedError<null, CmdError>(__TAURI_INVOKE("lock_wallet")),
	isUnlocked: () => typedError<boolean, CmdError>(__TAURI_INVOKE("is_unlocked")),
	listChains: () => typedError<ChainSummary[], CmdError>(__TAURI_INVOKE("list_chains")),
	listTokens: () => typedError<TokenSummary[], CmdError>(__TAURI_INVOKE("list_tokens")),
	// List every supported chain id alongside its default and (if any) overridden RPC.
	listRpcEndpoints: () => typedError<RpcEndpoint[], CmdError>(__TAURI_INVOKE("list_rpc_endpoints")),
	/**
	 *  Override the RPC URL for a given chain. The new endpoint takes effect
	 *  immediately for every subsequent IPC call.
	 */
	setRpcEndpoint: (chainId: string, url: string) => typedError<RpcEndpoint, CmdError>(__TAURI_INVOKE("set_rpc_endpoint", { chainId, url })),
	// Remove the user override for a chain, falling back to the built-in default.
	clearRpcEndpoint: (chainId: string) => typedError<RpcEndpoint, CmdError>(__TAURI_INVOKE("clear_rpc_endpoint", { chainId })),
	getAddress: (chainId: string) => typedError<string, CmdError>(__TAURI_INVOKE("get_address", { chainId })),
	getBalance: (chainId: string) => typedError<Amount, CmdError>(__TAURI_INVOKE("get_balance", { chainId })),
	getFeeOptions: (chainId: string) => typedError<FeeOption[], CmdError>(__TAURI_INVOKE("get_fee_options", { chainId })),
	sendNative: (args: SendNativeArgs) => typedError<SendNativeResult, CmdError>(__TAURI_INVOKE("send_native", { args })),
	// Sign and broadcast a token transfer (ERC-20 or TRC-20).
	sendToken: (args: SendTokenArgs) => typedError<SendTokenResult, CmdError>(__TAURI_INVOKE("send_token", { args })),
	getPrices: (ids: string[], currency: string | null) => typedError<{ [key in string]: PricePoint }, CmdError>(__TAURI_INVOKE("get_prices", { ids, currency })),
	// Currently persisted display currency (`"usd"` / `"eur"` / `"gbp"`).
	getFiatCurrency: () => typedError<string, CmdError>(__TAURI_INVOKE("get_fiat_currency")),
	// Persist a new display currency. Accepts `"usd"`, `"eur"`, or `"gbp"`.
	setFiatCurrency: (currency: string) => typedError<string, CmdError>(__TAURI_INVOKE("set_fiat_currency", { currency })),
	// Currently configured auto-lock timeout (minutes). `0` means disabled.
	getAutoLockMinutes: () => typedError<number, CmdError>(__TAURI_INVOKE("get_auto_lock_minutes")),
	/**
	 *  Persist a new auto-lock timeout. `0` disables auto-lock entirely.
	 *  Values above 1440 (24h) are clamped to discourage forever-unlocked sessions.
	 */
	setAutoLockMinutes: (minutes: number) => typedError<number, CmdError>(__TAURI_INVOKE("set_auto_lock_minutes", { minutes })),
	// Probe a single chain's effective endpoint and return latency / status.
	networkHealth: (chainId: string) => typedError<NetworkHealth, CmdError>(__TAURI_INVOKE("network_health", { chainId })),
	// Probe every supported chain in parallel.
	networkHealthAll: () => typedError<NetworkHealth[], CmdError>(__TAURI_INVOKE("network_health_all")),
	// Inspect (without revealing) the user's 1inch configuration.
	getExchangeSettings: () => typedError<ExchangeSettings, CmdError>(__TAURI_INVOKE("get_exchange_settings")),
	// Persist 1inch credentials. Pass `null` (or empty) to clear a field.
	setExchangeSettings: (args: ExchangeConfigArgs) => typedError<ExchangeSettings, CmdError>(__TAURI_INVOKE("set_exchange_settings", { args })),
	/**
	 *  Quote an EVM swap via 1inch v6.
	 * 
	 *  `chain_id` is the EIP-155 chain id (1 = mainnet, 137 = polygon, …).
	 *  Token addresses use 1inch's convention: the native asset is
	 *  `0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee`.
	 */
	exchangeQuote: (chainId: number, src: string, dst: string, amount: string) => typedError<Quote, CmdError>(__TAURI_INVOKE("exchange_quote", { chainId, src, dst, amount })),
	/**
	 *  Execute an EVM swap via 1inch v6.
	 * 
	 *  For ERC-20 source tokens this command also handles the on-chain
	 *  allowance: if the router's allowance is below the requested amount,
	 *  Atlas signs and broadcasts an `approve` transaction first, then the
	 *  swap. Both transactions use the wallet's pending nonce — the swap is
	 *  expected to land in the block immediately after the approval.
	 */
	exchangeSwap: (args: ExchangeSwapArgs) => typedError<ExchangeSwapResult, CmdError>(__TAURI_INVOKE("exchange_swap", { args })),
	listProfiles: () => typedError<ProfileSummary[], CmdError>(__TAURI_INVOKE("list_profiles")),
	activeProfile: () => typedError<{
	// Stable id (as string for JS).
	id: string,
	// Human-visible label.
	name: string,
	// `"hot"` or `"watch_only"`.
	kind: string,
	// Whether this profile can sign transactions.
	signing: boolean,
	// Creation timestamp.
	created_at: string,
	// Number of watched accounts (0 for hot profiles).
	watch_account_count: number,
} | null, CmdError>(__TAURI_INVOKE("active_profile")),
	switchProfile: (id: string) => typedError<null, CmdError>(__TAURI_INVOKE("switch_profile", { id })),
	renameProfile: (id: string, newName: string) => typedError<null, CmdError>(__TAURI_INVOKE("rename_profile", { id, newName })),
	deleteProfile: (id: string) => typedError<null, CmdError>(__TAURI_INVOKE("delete_profile", { id })),
	createWatchOnlyProfile: (args: CreateWatchOnlyArgs) => typedError<ProfileSummary, CmdError>(__TAURI_INVOKE("create_watch_only_profile", { args })),
	/**
	 *  Return the most-recent cached transactions. Pass chain_id = "" to query
	 *  across every chain.
	 */
	txHistoryList: (chainId: string, limit: number) => typedError<TxRecord[], CmdError>(__TAURI_INVOKE("tx_history_list", { chainId, limit })),
	/**
	 *  Update the on-disk status of a single tx (pending ? confirmed/failed).
	 *  The frontend can call this once a confirmation watcher resolves.
	 */
	txHistorySetStatus: (chainId: string, txid: string, status: string) => typedError<null, CmdError>(__TAURI_INVOKE("tx_history_set_status", { chainId, txid, status })),
	/**
	 *  Allow the UI to record a tx that didn't go through Atlas's send flow
	 *  (e.g. an external broadcast the user wants to track).
	 */
	txHistoryRecord: (record: TxRecord) => typedError<null, CmdError>(__TAURI_INVOKE("tx_history_record", { record })),
};

/* Types */
/**
 *  A precise on-chain amount: integer base units + asset metadata.
 * 
 *  `value` is denominated in the asset's smallest unit (sat for BTC,
 *  wei for ETH). We use `u128` as a JSON-friendly carrier for any
 *  realistic balance.
 */
export type Amount = {
	// Integer value in base units.
	value: number,
	// Asset this amount denominates.
	asset: Asset,
};

// A cryptocurrency asset (native or token).
export type Asset = {
	// Stable identifier — usually the lowercase ticker (`btc`, `eth`, `usdc`).
	id: string,
	// Display ticker, e.g. `BTC`.
	symbol: string,
	// Decimals (8 for BTC, 18 for ETH, 6 for USDC, …).
	decimals: number,
	// Optional logo URL/hint for the UI.
	logo: string | null,
};

export type ChainSummary = {
	id: string,
	display_name: string,
	symbol: string,
	decimals: number,
	family: string,
	enabled_by_default: boolean,
};

export type CmdError = { kind: "NotInitialized"; message: string } | { kind: "Locked" } | { kind: "InvalidInput"; message: string } | { kind: "Wallet"; message: string } | { kind: "Chain"; message: string } | { kind: "Io"; message: string } | { kind: "Profile"; message: string };

export type CreateWalletArgs = {
	password: string,
	word_count: number,
	/**
	 *  Optional human-friendly profile name. Defaults to `"Default"` for the
	 *  first wallet, otherwise required.
	 */
	name?: string | null,
};

export type CreateWatchOnlyArgs = {
	name: string,
	accounts: WatchAccount[],
};

export type ExchangeConfigArgs = {
	api_key: string | null,
	base_url: string | null,
};

export type ExchangeSettings = {
	api_key_set: boolean,
	base_url: string,
};

export type ExchangeSwapArgs = {
	chain_id: number,
	src: string,
	dst: string,
	// Source amount, base units, decimal string.
	amount: string,
	// Maximum slippage in basis points (100 = 1%).
	slippage_bps: number,
	// `slow|normal|fast` or a raw decimal wei gas-price.
	fee_level: string,
};

export type ExchangeSwapResult = {
	// Final swap transaction hash.
	txid: string,
	// If a pre-approve was needed (ERC-20 source), this is its tx hash.
	approve_txid: string | null,
	// Estimated destination amount, base units, decimal string.
	to_amount: string,
};

// Three canonical fee tiers presented to the user.
export type FeeOption = {
	// `"slow" | "normal" | "fast"`.
	level: string,
	// Estimated fee for a typical transaction.
	estimated_fee: Amount,
	// Estimated time-to-confirm in seconds.
	eta_seconds: number,
	// Implementation-defined hint payload (e.g. sat/vB or gas price), JSON-encoded as string for FFI simplicity.
	raw_hint: string,
};

export type ImportWalletArgs = {
	password: string,
	phrase: string,
	passphrase?: string | null,
	name?: string | null,
};

// Result of a single `network_health` probe.
export type NetworkHealth = {
	// Chain id this report describes (`"btc"`, `"eth"`, …).
	chain_id: string,
	// Effective endpoint URL we probed.
	endpoint: string,
	// Whether the endpoint URL is the user's override (`true`) or built-in default.
	is_user_override: boolean,
	// Number of samples sent.
	samples: number,
	// Number of samples that returned successfully.
	successes: number,
	// Median latency across successful samples, in milliseconds.
	latency_p50_ms: number | null,
	// 95th percentile latency across successful samples, in milliseconds.
	latency_p95_ms: number | null,
	// Most recently observed head height (block / slot number).
	head_height: number | null,
	// Bucketed status for the UI.
	status: NetworkStatus,
};

// Per-chain status bucket surfaced to the UI as a green / amber / red dot.
export type NetworkStatus = 
// Endpoint is reachable and responsive.
"synced" | 
// Endpoint responds but is slow or losing samples.
"lagging" | 
// All samples failed.
"offline";

// A single cached price observation.
export type PricePoint = {
	// Price in the requested fiat currency.
	price: number,
	// 24h change as a percentage.
	change_24h: number,
};

// Frontend-friendly summary of a profile.
export type ProfileSummary = {
	// Stable id (as string for JS).
	id: string,
	// Human-visible label.
	name: string,
	// `"hot"` or `"watch_only"`.
	kind: string,
	// Whether this profile can sign transactions.
	signing: boolean,
	// Creation timestamp.
	created_at: string,
	// Number of watched accounts (0 for hot profiles).
	watch_account_count: number,
};

// 1inch v6 quote response, lifted into a stable shape.
export type Quote = {
	// Source token address (lowercase 0x…).
	from_token: string,
	// Destination token address.
	to_token: string,
	// Source amount, base units, decimal string.
	from_amount: string,
	// Estimated destination amount, base units, decimal string.
	to_amount: string,
	// Estimated gas units for the swap (advisory).
	estimated_gas: number,
	// Optional names of protocols routed through.
	protocols: string[],
};

export type RpcEndpoint = {
	chain_id: string,
	// Built-in default URL Atlas falls back to when no override is set.
	default_url: string | null,
	// User-configured override, if any.
	override_url: string | null,
	// The URL providers are actually dialing right now.
	effective_url: string | null,
};

export type SendNativeArgs = {
	chain_id: string,
	to: string,
	amount: string,
	fee_level: string,
};

export type SendNativeResult = {
	txid: string,
	fee: Amount,
};

export type SendTokenArgs = {
	// Token id from the registry (e.g. `usdt-erc20`).
	token_id: string,
	to: string,
	// Token amount in base units (string-encoded u128).
	amount: string,
	fee_level: string,
};

export type SendTokenResult = {
	txid: string,
	// Network fee paid in the chain's native asset.
	fee: Amount,
};

export type TokenSummary = {
	id: string,
	symbol: string,
	display_name: string,
	chain_id: string,
	contract: string,
	decimals: number,
	standard: string,
	enabled_by_default: boolean,
};

// One on-chain transaction the user (or Atlas itself) initiated.
export type TxRecord = {
	// Transaction id / hash, lower-case hex (no `0x` for BTC; with `0x` for EVM).
	txid: string,
	// Chain id (`"btc"`, `"eth"`, `"sol"`, …).
	chain_id: string,
	/**
	 *  `"send"` or `"receive"`. Atlas only writes `"send"` itself today;
	 *  `"receive"` rows are reserved for future explorer-driven enrichment.
	 */
	direction: string,
	// Other party's address.
	counterparty: string,
	// Amount in base units, decimal-string (u128-friendly).
	amount: string,
	// Asset ticker (`"BTC"`, `"ETH"`, `"USDT"`, …).
	asset: string,
	// Network fee paid, decimal string in the chain's native asset base units.
	fee: string,
	// Unix timestamp (seconds) when the tx was broadcast.
	timestamp: number,
	// `"pending"`, `"confirmed"`, or `"failed"`.
	status: string,
	// Optional user-supplied note.
	memo: string | null,
};

// A `(chain_id, address)` pair tracked by a watch-only profile.
export type WatchAccount = {
	// Chain identifier (e.g. `"btc"`, `"eth"`, `"polygon"`).
	chain_id: string,
	// Public address (no private key material).
	address: string,
	// Optional human label.
	label?: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

