// AUTO-GENERATED by tauri-specta — do not edit by hand.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	// `true` if the registry currently has at least one hot profile.
	vaultExists: () => typedError<boolean, CmdError>(__TAURI_INVOKE("vault_exists")),
	createWallet: (args: CreateWalletArgs) => typedError<string, CmdError>(__TAURI_INVOKE("create_wallet", { args })),
	importWallet: (args: ImportWalletArgs) => typedError<null, CmdError>(__TAURI_INVOKE("import_wallet", { args })),
	unlockWallet: (password: string) => typedError<null, CmdError>(__TAURI_INVOKE("unlock_wallet", { password })),
	lockWallet: () => typedError<null, CmdError>(__TAURI_INVOKE("lock_wallet")),
	isUnlocked: () => typedError<boolean, CmdError>(__TAURI_INVOKE("is_unlocked")),
	listChains: () => typedError<ChainSummary[], CmdError>(__TAURI_INVOKE("list_chains")),
	listTokens: () => typedError<TokenSummary[], CmdError>(__TAURI_INVOKE("list_tokens")),
	/**
	 *  Curated token-list URLs Atlas ships with by default. The frontend
	 *  uses this to populate the "Refresh from tokenlists.org" picker.
	 */
	tokenListDefaultUrls: () => typedError<string[], CmdError>(__TAURI_INVOKE("token_list_default_urls")),
	/**
	 *  Fetch a Uniswap-format token list from `url` and return the parsed
	 *  tokens for any chain Atlas supports. Network errors and invalid JSON
	 *  surface as [`CmdError::InvalidInput`].
	 */
	tokenListFetch: (url: string) => typedError<OwnedTokenMeta[], CmdError>(__TAURI_INVOKE("token_list_fetch", { url })),
	/**
	 *  Add a custom user-imported token. Validates contract format (`0x` +
	 *  40 hex chars for EVM, base58 for Tron) before persisting so the UI
	 *  can't poison the local DB with garbage.
	 */
	tokenAddCustom: (chainId: string, contract: string, symbol: string, displayName: string, decimals: number, logoUri: string | null) => typedError<null, CmdError>(__TAURI_INVOKE("token_add_custom", { chainId, contract, symbol, displayName, decimals, logoUri })),
	// List custom tokens for `chain_id` (or all chains when empty).
	tokenListCustom: (chainId: string) => typedError<CustomToken[], CmdError>(__TAURI_INVOKE("token_list_custom", { chainId })),
	// Remove one custom token. Returns `true` if a row was deleted.
	tokenRemoveCustom: (chainId: string, contract: string) => typedError<boolean, CmdError>(__TAURI_INVOKE("token_remove_custom", { chainId, contract })),
	// List every supported chain id alongside its default and (if any) overridden RPC.
	listRpcEndpoints: () => typedError<RpcEndpoint[], CmdError>(__TAURI_INVOKE("list_rpc_endpoints")),
	/**
	 *  Override the RPC URL for a given chain. The new endpoint takes effect
	 *  immediately for every subsequent IPC call.
	 */
	setRpcEndpoint: (chainId: string, url: string) => typedError<RpcEndpoint, CmdError>(__TAURI_INVOKE("set_rpc_endpoint", { chainId, url })),
	// Remove the user override for a chain, falling back to the built-in default.
	clearRpcEndpoint: (chainId: string) => typedError<RpcEndpoint, CmdError>(__TAURI_INVOKE("clear_rpc_endpoint", { chainId })),
	getAddress: (chainId: string) => typedError<string, CmdError>(__TAURI_INVOKE("get_address", { chainId })),
	getBalance: (chainId: string) => typedError<Amount, CmdError>(__TAURI_INVOKE("get_balance", { chainId })),
	getFeeOptions: (chainId: string) => typedError<FeeOption[], CmdError>(__TAURI_INVOKE("get_fee_options", { chainId })),
	sendNative: (args: SendNativeArgs) => typedError<SendNativeResult, CmdError>(__TAURI_INVOKE("send_native", { args })),
	// Sign and broadcast a token transfer (ERC-20 or TRC-20).
	sendToken: (args: SendTokenArgs) => typedError<SendTokenResult, CmdError>(__TAURI_INVOKE("send_token", { args })),
	getPrices: (ids: string[], currency: string | null) => typedError<{ [key in string]: PricePoint }, CmdError>(__TAURI_INVOKE("get_prices", { ids, currency })),
	// Currently persisted display currency (`"usd"` / `"eur"` / `"gbp"`).
	getFiatCurrency: () => typedError<string, CmdError>(__TAURI_INVOKE("get_fiat_currency")),
	// Persist a new display currency. Accepts `"usd"`, `"eur"`, or `"gbp"`.
	setFiatCurrency: (currency: string) => typedError<string, CmdError>(__TAURI_INVOKE("set_fiat_currency", { currency })),
	// Currently configured auto-lock timeout (minutes). `0` means disabled.
	getAutoLockMinutes: () => typedError<number, CmdError>(__TAURI_INVOKE("get_auto_lock_minutes")),
	/**
	 *  Persist a new auto-lock timeout. `0` disables auto-lock entirely.
	 *  Values above 1440 (24h) are clamped to discourage forever-unlocked sessions.
	 */
	setAutoLockMinutes: (minutes: number) => typedError<number, CmdError>(__TAURI_INVOKE("set_auto_lock_minutes", { minutes })),
	/**
	 *  Currently configured anti-phishing phrase. Surfaced on every
	 *  unlock screen so users can tell a phishing UI from the real
	 *  Atlas.
	 */
	getAntiPhishingPhrase: () => typedError<string | null, CmdError>(__TAURI_INVOKE("get_anti_phishing_phrase")),
	/**
	 *  Set or clear the anti-phishing phrase. Pass `None` / empty
	 *  string to disable the feature.
	 */
	setAntiPhishingPhrase: (phrase: string | null) => typedError<string | null, CmdError>(__TAURI_INVOKE("set_anti_phishing_phrase", { phrase })),
	// Combined biometric availability + user preference.
	biometricStatus: () => typedError<BiometricStatus, CmdError>(__TAURI_INVOKE("biometric_status")),
	/**
	 *  Persist the user's biometric-unlock preference. The actual
	 *  platform check happens at unlock time; this command only
	 *  records the preference.
	 */
	setBiometricUnlockEnabled: (enabled: boolean) => typedError<boolean, CmdError>(__TAURI_INVOKE("set_biometric_unlock_enabled", { enabled })),
	// Current recovery-drill status (due / interval / last).
	recoveryDrillStatus: () => typedError<RecoveryDrillStatus, CmdError>(__TAURI_INVOKE("recovery_drill_status")),
	/**
	 *  Update the recovery-drill reminder interval. Pass `0` to
	 *  disable the reminder. Values above 365 days are clamped.
	 */
	setRecoveryDrillIntervalDays: (days: number) => typedError<number, CmdError>(__TAURI_INVOKE("set_recovery_drill_interval_days", { days })),
	/**
	 *  Record that the user just successfully verified their seed
	 *  phrase. The frontend is responsible for actually performing
	 *  the verification (showing a few random words and checking the
	 *  user types them back).
	 */
	recordRecoveryDrillCompleted: () => typedError<null, CmdError>(__TAURI_INVOKE("record_recovery_drill_completed")),
	// Read the current swap-fee configuration.
	getSwapFeeConfig: () => typedError<SwapFeeConfig, CmdError>(__TAURI_INVOKE("get_swap_fee_config")),
	// Update Atlas's swap-fee bps. Clamped to `[0, 100]` (1 %).
	setSwapFeeBps: (bps: number) => typedError<number, CmdError>(__TAURI_INVOKE("set_swap_fee_bps", { bps })),
	// Persist (or clear) the THORChain affiliate THORName.
	setThorchainAffiliate: (name: string | null) => typedError<string | null, CmdError>(__TAURI_INVOKE("set_thorchain_affiliate", { name })),
	/**
	 *  Whether the Ethereum-mainnet RPC currently points at the
	 *  Flashbots Protect endpoint.
	 */
	flashbotsProtectEnabled: () => typedError<boolean, CmdError>(__TAURI_INVOKE("flashbots_protect_enabled")),
	/**
	 *  Toggle Flashbots Protect for Ethereum mainnet. When enabled,
	 *  the wallet sets the `ethereum` RPC override to the Flashbots
	 *  Protect URL; when disabled, the override is cleared so Atlas
	 *  falls back to its default mainnet RPC. Other chains are
	 *  unaffected.
	 */
	setFlashbotsProtect: (enabled: boolean) => typedError<boolean, CmdError>(__TAURI_INVOKE("set_flashbots_protect", { enabled })),
	getMoonpayConfig: () => typedError<MoonPayConfig, CmdError>(__TAURI_INVOKE("get_moonpay_config")),
	setMoonpayConfig: (args: MoonPayConfigInput) => typedError<MoonPayConfig, CmdError>(__TAURI_INVOKE("set_moonpay_config", { args })),
	/**
	 *  Build a (possibly signed) MoonPay Buy widget URL using the persisted
	 *  configuration. The returned URL is intended to be opened in the system
	 *  browser.
	 */
	buildMoonpayBuyUrl: (args: MoonPayBuyArgs) => typedError<string, CmdError>(__TAURI_INVOKE("build_moonpay_buy_url", { args })),
	/**
	 *  Build a (possibly signed) MoonPay Sell widget URL using the persisted
	 *  configuration. The user lands on MoonPay, sells crypto for fiat, and
	 *  MoonPay handles KYC + bank/card payout.
	 */
	buildMoonpaySellUrl: (args: MoonPaySellArgs) => typedError<string, CmdError>(__TAURI_INVOKE("build_moonpay_sell_url", { args })),
	// Build an N-of-M `wsh(sortedmulti)` descriptor wallet from a policy.
	multisigBtcBuildDescriptor: (policy: MultisigPolicy) => typedError<MultisigWallet, CmdError>(__TAURI_INVOKE("multisig_btc_build_descriptor", { policy })),
	/**
	 *  Derive the receive (`change=false`) or change (`change=true`) address
	 *  at `index` for a previously-built multisig wallet.
	 */
	multisigBtcDeriveAddress: (wallet: MultisigWallet, change: boolean, index: number) => typedError<string, CmdError>(__TAURI_INVOKE("multisig_btc_derive_address", { wallet, change, index })),
	// Decode a base64 PSBT and return a UI-friendly summary.
	multisigBtcPsbtSummary: (psbtB64: string) => typedError<PsbtSummary, CmdError>(__TAURI_INVOKE("multisig_btc_psbt_summary", { psbtB64 })),
	/**
	 *  Combine partially-signed PSBTs (one from each co-signer) into a
	 *  single PSBT carrying every collected signature.
	 */
	multisigBtcPsbtCombine: (parts: string[]) => typedError<string, CmdError>(__TAURI_INVOKE("multisig_btc_psbt_combine", { parts })),
	/**
	 *  Finalise a fully-signed PSBT and return the raw broadcast-ready
	 *  transaction hex.
	 */
	multisigBtcPsbtFinalize: (psbtB64: string) => typedError<string, CmdError>(__TAURI_INVOKE("multisig_btc_psbt_finalize", { psbtB64 })),
	/**
	 *  Build a shareable `atlas-msig://signer?...` invite URI for a
	 *  co-signer. The receiving wallet decodes it and gets a ready-to-use
	 *  `MultisigSigner` (xpub + origin + fingerprint + optional label).
	 */
	multisigBtcBuildInvite: (invite: CoSignerInvite) => typedError<string, CmdError>(__TAURI_INVOKE("multisig_btc_build_invite", { invite })),
	/**
	 *  Parse a co-signer invite URI received from a partner. Rejects
	 *  invites whose embedded xpub doesn't decode (cheap tamper check).
	 */
	multisigBtcParseInvite: (uri: string) => typedError<CoSignerInvite, CmdError>(__TAURI_INVOKE("multisig_btc_parse_invite", { uri })),
	/**
	 *  Compute the canonical EIP-712 `safeTxHash` and `domainSeparator` for
	 *  a Safe transaction. Co-signers verify these before signing so they
	 *  know exactly which chain + Safe + payload their signature commits to.
	 */
	multisigEvmSafeTxHash: (safeAddress: string, chainId: number, tx: SafeTx) => typedError<SafeTxHashes, CmdError>(__TAURI_INVOKE("multisig_evm_safe_tx_hash", { safeAddress, chainId, tx })),
	/**
	 *  Pack collected `(signer, signature)` pairs into the contiguous bytes
	 *  blob `Safe.execTransaction` expects. Signatures are sorted by signer
	 *  address ascending — the order Safe v1.3+ requires.
	 */
	multisigEvmPackSignatures: (sigs: ([string, string])[]) => typedError<string, CmdError>(__TAURI_INVOKE("multisig_evm_pack_signatures", { sigs })),
	/**
	 *  Compute the canonical EntryPoint v0.6 `userOpHash` a smart-account
	 *  owner must sign before submitting to a bundler.
	 */
	aaUserOpHash: (entryPoint: string, chainId: number, op: UserOperation) => typedError<UserOpHashes, CmdError>(__TAURI_INVOKE("aa_user_op_hash", { entryPoint, chainId, op })),
	/**
	 *  Encode `(target, value, data)` as ABI calldata for a SimpleAccount's
	 *  `execute(address,uint256,bytes)` entry — the canonical inner-call
	 *  dispatcher used by virtually every ERC-4337 account implementation.
	 */
	aaEncodeExecuteCalldata: (target: string, value: string, data: string) => typedError<string, CmdError>(__TAURI_INVOKE("aa_encode_execute_calldata", { target, value, data })),
	/**
	 *  Split a hex-encoded secret into `total` Shamir shares with the
	 *  given recovery `threshold`. Uses OS RNG for the polynomial
	 *  coefficients so the same secret produces fresh shares every call.
	 */
	shamirSplit: (secretHex: string, threshold: number, total: number) => typedError<Share[], CmdError>(__TAURI_INVOKE("shamir_split", { secretHex, threshold, total })),
	/**
	 *  Recover a secret (hex-encoded) from at least `threshold` Shamir
	 *  shares previously produced by `shamir_split`.
	 */
	shamirCombine: (shares: Share[]) => typedError<string, CmdError>(__TAURI_INVOKE("shamir_combine", { shares })),
	// Parse a `wc:` v2 pairing URI into its components.
	wcParseUri: (uri: string) => typedError<WcUri, CmdError>(__TAURI_INVOKE("wc_parse_uri", { uri })),
	// Re-emit a `wc:` v2 URI from a parsed `WcUri`.
	wcBuildUri: (uri: WcUri) => typedError<string, CmdError>(__TAURI_INVOKE("wc_build_uri", { uri })),
	/**
	 *  Evaluate a candidate URL against the curated dApp registry. Used by
	 *  the in-app browser before rendering a third-party origin.
	 */
	dappAssessOrigin: (url: string) => typedError<DappAssessment, CmdError>(__TAURI_INVOKE("dapp_assess_origin", { url })),
	// Return the built-in curated dApp list (UI directory / search).
	dappListCurated: () => typedError<DappEntry[], CmdError>(__TAURI_INVOKE("dapp_list_curated")),
	/**
	 *  Analyse an arbitrary origin URL using the built-in defence config
	 *  (curated DEX/NFT/wallet brand list) plus typosquat / homoglyph /
	 *  Punycode heuristics. The dApp registry handles the curated good
	 *  origins; this command catches the long tail.
	 */
	phishingAnalyzeDefault: (origin: string) => typedError<PhishingReport, CmdError>(__TAURI_INVOKE("phishing_analyze_default", { origin })),
	// Analyse a dApp origin URL for phishing indicators.
	phishingAnalyze: (origin: string, config: PhishingConfig) => typedError<PhishingReport, CmdError>(__TAURI_INVOKE("phishing_analyze", { origin, config })),
	/**
	 *  Aggregate a flat list of owned NFTs into the gallery view used by
	 *  the UI (collection grouping, value totals, optional spam filter).
	 */
	nftGalleryView: (items: OwnedNft[], filter: GalleryFilter) => typedError<GalleryView, CmdError>(__TAURI_INVOKE("nft_gallery_view", { items, filter })),
	/**
	 *  Aggregate a user's delegations on one chain into a `ChainPosition`
	 *  (totals + stake-weighted net APR). Validators are needed so we can
	 *  resolve each delegation's APR.
	 */
	stakingAggregateChain: (chain: StakingChain, delegations: Delegation[], validators: Validator[]) => typedError<ChainPosition, CmdError>(__TAURI_INVOKE("staking_aggregate_chain", { chain, delegations, validators })),
	/**
	 *  Pick a sensible validator from a candidate list (active +
	 *  reasonable commission + decentralisation-friendly tiebreakers).
	 */
	stakingRecommendValidator: (validators: Validator[]) => typedError<{
	chain: StakingChain,
	// Chain-native identifier (vote pubkey, valoper address, pool id, etc).
	id: string,
	name: string,
	// Commission in basis points (10000 = 100%).
	commission_bps: number,
	/**
	 *  Self-reported total stake in the network's base units
	 *  (lamports, uatom, lovelace, plancks, wei). Stored as f64 so
	 *  extreme totals (Polkadot validators) round-trip cleanly through
	 *  JSON without needing u128.
	 */
	total_stake: number,
	/**
	 *  Net APR (after the validator's commission) as a fraction
	 *  (0.045 = 4.5%).
	 */
	net_apr: number,
	/**
	 *  Whether this validator is currently active (in the active set
	 *  / not jailed / not slashed-out).
	 */
	active: boolean,
	/**
	 *  True if Atlas considers this validator decentralisation-friendly
	 *  (small share of total stake, no jail history). Used to bias the
	 *  recommendation list without hiding alternatives.
	 */
	recommended: boolean,
} | null, CmdError>(__TAURI_INVOKE("staking_recommend_validator", { validators })),
	/**
	 *  Convert a nominal APR to APY using the chain's typical compounding
	 *  frequency (saves the UI from hard-coding magic numbers).
	 */
	stakingAprToApy: (chain: StakingChain, apr: number) => typedError<number, CmdError>(__TAURI_INVOKE("staking_apr_to_apy", { chain, apr })),
	/**
	 *  Apply UI filters (chain / direction / status / date / asset /
	 *  query) and return rows newest-first.
	 */
	txHistoryFilter: (rows: Tx[], filter: HistoryFilter) => typedError<Tx[], CmdError>(__TAURI_INVOKE("tx_history_filter", { rows, filter })),
	/**
	 *  Aggregate a (typically already-filtered) row set into per-asset
	 *  and per-chain totals plus first/last timestamps.
	 */
	txHistorySummarise: (rows: Tx[]) => typedError<HistorySummary, CmdError>(__TAURI_INVOKE("tx_history_summarise", { rows })),
	// Render a row set as RFC-4180-style CSV, ready for download.
	txHistoryExportCsv: (rows: Tx[]) => typedError<string, CmdError>(__TAURI_INVOKE("tx_history_export_csv", { rows })),
	/**
	 *  Aggregate independent price feeds into a single median quote with
	 *  outlier rejection. Quotes are pre-fetched by the frontend (or by
	 *  other Tauri commands) so this command itself does no I/O.
	 */
	priceOracleAggregate: (quotes: SourceQuote[], maxDeviationBps: number) => typedError<AggregatedPrice, CmdError>(__TAURI_INVOKE("price_oracle_aggregate", { quotes, maxDeviationBps })),
	/**
	 *  Score every approval against the (curated) config and return rows
	 *  sorted Critical first.
	 */
	approvalsAnalyze: (approvals: Approval[], config: ApprovalConfig, now: number) => typedError<ApprovalRisk[], CmdError>(__TAURI_INVOKE("approvals_analyze", { approvals, config, now })),
	// Aggregate per-chain risk counts for the dashboard header.
	approvalsSummarise: (rows: ApprovalRisk[]) => typedError<ApprovalSummary[], CmdError>(__TAURI_INVOKE("approvals_summarise", { rows })),
	// Decode raw EVM calldata into a structured action description.
	calldataDecode: (data: string) => typedError<DecodedCall, CmdError>(__TAURI_INVOKE("calldata_decode", { data })),
	/**
	 *  Flag incoming transfers from addresses that visually mimic
	 *  addresses the user has previously sent funds to.
	 */
	poisoningDetect: (transfers: IncomingTransfer[], trusted: TrustedCounterparty[], config: PoisonConfig) => typedError<PoisonAlert[], CmdError>(__TAURI_INVOKE("poisoning_detect", { transfers, trusted, config })),
	/**
	 *  Live-input check for the Send page: compare a candidate recipient
	 *  against every address in the user's contact book and return any
	 *  look-alikes whose hex prefix/suffix overlap exceeds the defaults.
	 */
	poisoningCheckCandidate: (candidate: string) => typedError<MimicMatch[], CmdError>(__TAURI_INVOKE("poisoning_check_candidate", { candidate })),
	// Classify an EIP-712 typed-data signing request before the user signs.
	eip712Classify: (json: string) => typedError<Eip712Report, CmdError>(__TAURI_INVOKE("eip712_classify", { json })),
	/**
	 *  Check an address against the user's blocklist. Always returns a
	 *  verdict; an unparseable address is reported as `Clean` so we never
	 *  throw on user input.
	 */
	blocklistCheck: (address: string) => typedError<BlocklistVerdict, CmdError>(__TAURI_INVOKE("blocklist_check", { address })),
	// Sorted snapshot of every entry currently in the blocklist.
	blocklistList: () => typedError<BlocklistEntry[], CmdError>(__TAURI_INVOKE("blocklist_list")),
	// Add (or overwrite) one entry. Returns the normalised key.
	blocklistAdd: (entry: BlocklistEntry) => typedError<string, CmdError>(__TAURI_INVOKE("blocklist_add", { entry })),
	// Remove one entry. Returns true if it was present.
	blocklistRemove: (address: string) => typedError<boolean, CmdError>(__TAURI_INVOKE("blocklist_remove", { address })),
	/**
	 *  Bulk-merge a JSON array of entries (e.g. from a curated feed).
	 *  Returns the number of entries written.
	 */
	blocklistImportJson: (json: string) => typedError<number, CmdError>(__TAURI_INVOKE("blocklist_import_json", { json })),
	// Compute realized + unrealized P&L over a list of trades.
	pnlCompute: (trades: Trade[], prices: { [key in string]: number }, method: AccountingMethod) => typedError<PortfolioReport, CmdError>(__TAURI_INVOKE("pnl_compute", { trades, prices, method })),
	// List every recorded trade, oldest-first.
	tradesList: () => typedError<Trade[], CmdError>(__TAURI_INVOKE("trades_list")),
	// Append a trade to the local history and persist to disk.
	tradesAdd: (trade: Trade) => typedError<number, CmdError>(__TAURI_INVOKE("trades_add", { trade })),
	/**
	 *  Remove the trade at `index` (0-based, oldest-first ordering).
	 *  Returns whether a trade was removed.
	 */
	tradesRemove: (index: number) => typedError<boolean, CmdError>(__TAURI_INVOKE("trades_remove", { index })),
	// Clear the entire trade history.
	tradesClear: () => typedError<null, CmdError>(__TAURI_INVOKE("trades_clear")),
	/**
	 *  Bulk-import a JSON array of `Trade` objects. Returns the number of
	 *  rows added.
	 */
	tradesImportJson: (json: string) => typedError<number, CmdError>(__TAURI_INVOKE("trades_import_json", { json })),
	// Compute P&L over the persisted trade history.
	tradesComputePnl: (prices: { [key in string]: number }, method: AccountingMethod) => typedError<PortfolioReport, CmdError>(__TAURI_INVOKE("trades_compute_pnl", { prices, method })),
	// Parse a BIP-21 / EIP-681 payment URI scanned from a QR code.
	payuriParse: (input: string) => typedError<PaymentIntent, CmdError>(__TAURI_INVOKE("payuri_parse", { input })),
	/**
	 *  Suggest Slow / Standard / Fast EIP-1559 fee tiers from a recent
	 *  base-fee and a priority-fee history.
	 */
	feesEip1559Suggest: (baseFeePerGas: string, recentPriorityFees: string[]) => typedError<Eip1559Suggestions, CmdError>(__TAURI_INVOKE("fees_eip1559_suggest", { baseFeePerGas, recentPriorityFees })),
	// Bump an EIP-1559 suggestion by >=10% for replacing a stuck tx.
	feesBumpForReplacement: (suggestion: Eip1559Suggestion) => typedError<Eip1559Suggestion, CmdError>(__TAURI_INVOKE("fees_bump_for_replacement", { suggestion })),
	// Total UTXO fee in sats given a sat/vB rate and a vsize estimate.
	feesUtxoSats: (satPerVbyte: number, vsize: number) => typedError<number, CmdError>(__TAURI_INVOKE("fees_utxo_sats", { satPerVbyte, vsize })),
	// Cheap heuristic: does this string look like an ENS name?
	ensLooksLikeEns: (name: string) => typedError<boolean, CmdError>(__TAURI_INVOKE("ens_looks_like_ens", { name })),
	// UTS-46 normalise an ENS name (lowercase + label validation).
	ensNormalise: (name: string) => typedError<string, CmdError>(__TAURI_INVOKE("ens_normalise", { name })),
	// Compute the EIP-137 namehash of an ENS name as a 0x-prefixed hex string.
	ensNamehash: (name: string) => typedError<string, CmdError>(__TAURI_INVOKE("ens_namehash", { name })),
	/**
	 *  USD-denominated gas cost for an EVM tx.
	 * 
	 *  `effective_gas_price_wei` is passed as a decimal string because
	 *  Tauri's specta layer can't round-trip u128 directly.
	 *  `native_price_usd_micro` is the native-token price scaled by 1e6
	 *  (e.g. $1234.567890 → 1_234_567_890).
	 */
	gascostEstimate: (gasUsed: number, effectiveGasPriceWei: string, nativePriceUsdMicro: number) => typedError<GasCost, CmdError>(__TAURI_INVOKE("gascost_estimate", { gasUsed, effectiveGasPriceWei, nativePriceUsdMicro })),
	// Format a wei amount as a fixed-decimal native-token string.
	gascostFormatEth: (wei: string, decimals: number) => typedError<string, CmdError>(__TAURI_INVOKE("gascost_format_eth", { wei, decimals })),
	// Score a portfolio's concentration and return per-position weights.
	diversificationAnalyse: (holdings: Holding[]) => typedError<DiversificationReport, CmdError>(__TAURI_INVOKE("diversification_analyse", { holdings })),
	// Validate slippage bps + deadline seconds. Returns the canonicalised pair.
	slippageValidate: (slippageBps: number, deadlineSecs: number) => typedError<SwapSettings, CmdError>(__TAURI_INVOKE("slippage_validate", { slippageBps, deadlineSecs })),
	// Bucket a slippage value into Low / Normal / High / Reckless.
	slippageBand: (slippageBps: number) => typedError<SlippageBand, CmdError>(__TAURI_INVOKE("slippage_band", { slippageBps })),
	/**
	 *  Floor `amountOutMin` from a quote and slippage tolerance.
	 * 
	 *  `amount_out_quote` is a u128 passed as a decimal string so it
	 *  survives the JS bridge.
	 */
	slippageMinOut: (amountOutQuote: string, slippageBps: number) => typedError<string, CmdError>(__TAURI_INVOKE("slippage_min_out", { amountOutQuote, slippageBps })),
	// Ceiling `amountInMax` from a quote and slippage tolerance.
	slippageMaxIn: (amountInQuote: string, slippageBps: number) => typedError<string, CmdError>(__TAURI_INVOKE("slippage_max_in", { amountInQuote, slippageBps })),
	// Compute the absolute deadline timestamp (unix seconds).
	slippageDeadlineUnix: (nowUnix: number, deadlineSecs: number) => typedError<number, CmdError>(__TAURI_INVOKE("slippage_deadline_unix", { nowUnix, deadlineSecs })),
	// Locale-aware currency formatter (e.g. "$1,234.56").
	fmtCurrency: (amount: number, code: string, localeTag: string, decimals: number) => typedError<string, CmdError>(__TAURI_INVOKE("fmt_currency", { amount, code, localeTag, decimals })),
	// Compact number formatter (e.g. 1234567 -> "1.23M").
	fmtCompact: (value: number) => typedError<string, CmdError>(__TAURI_INVOKE("fmt_compact", { value })),
	// Format a base-unit decimal string into a human token amount.
	fmtTokenAmount: (baseUnits: string, decimals: number, maxSignificant: number) => typedError<string, CmdError>(__TAURI_INVOKE("fmt_token_amount", { baseUnits, decimals, maxSignificant })),
	// Shorten a 0x address to "0x1234\u{2026}abcd" form.
	fmtTruncateAddress: (addr: string) => typedError<string, CmdError>(__TAURI_INVOKE("fmt_truncate_address", { addr })),
	// List all stored tx-notes.
	txnotesList: () => typedError<TxNote[], CmdError>(__TAURI_INVOKE("txnotes_list")),
	// Get a single note by chain + txid (case-insensitive).
	txnotesGet: (chain: Chain, txid: string) => typedError<{
	chain: Chain,
	txid: string,
	note: string,
	tags: string[],
} | null, CmdError>(__TAURI_INVOKE("txnotes_get", { chain, txid })),
	// Insert or replace a tx-note. Empty note + empty tags removes it.
	txnotesUpsert: (chain: Chain, txid: string, note: string, tags: string[]) => typedError<null, CmdError>(__TAURI_INVOKE("txnotes_upsert", { chain, txid, note, tags })),
	// Remove a tx-note. Returns whether one existed.
	txnotesRemove: (chain: Chain, txid: string) => typedError<boolean, CmdError>(__TAURI_INVOKE("txnotes_remove", { chain, txid })),
	// List notes that carry a given tag (case-insensitive).
	txnotesListByTag: (tag: string) => typedError<TxNote[], CmdError>(__TAURI_INVOKE("txnotes_list_by_tag", { tag })),
	// Distinct, sorted list of every tag used across all notes.
	txnotesAllTags: () => typedError<string[], CmdError>(__TAURI_INVOKE("txnotes_all_tags")),
	// All contacts, ordered by name.
	contactsList: () => typedError<Contact[], CmdError>(__TAURI_INVOKE("contacts_list")),
	// Get one contact by uuid.
	contactsGet: (id: string) => typedError<{
	id: string,
	name: string,
	note: string,
	addresses: ContactAddress[],
} | null, CmdError>(__TAURI_INVOKE("contacts_get", { id })),
	// Add a new contact and return the assigned uuid.
	contactsAdd: (name: string, note: string, addresses: ContactAddress[]) => typedError<string, CmdError>(__TAURI_INVOKE("contacts_add", { name, note, addresses })),
	// Update an existing contact.
	contactsUpdate: (id: string, name: string, note: string, addresses: ContactAddress[]) => typedError<null, CmdError>(__TAURI_INVOKE("contacts_update", { id, name, note, addresses })),
	// Remove a contact. Returns whether one existed.
	contactsRemove: (id: string) => typedError<boolean, CmdError>(__TAURI_INVOKE("contacts_remove", { id })),
	// Find the contact (if any) that owns this `chain`+`address`.
	contactsFindByAddress: (chain: ContactChain, address: string) => typedError<{
	id: string,
	name: string,
	note: string,
	addresses: ContactAddress[],
} | null, CmdError>(__TAURI_INVOKE("contacts_find_by_address", { chain, address })),
	// Case-insensitive substring search across name + note.
	contactsSearch: (query: string) => typedError<Contact[], CmdError>(__TAURI_INVOKE("contacts_search", { query })),
	// Append a redactable event to the in-memory ring buffer.
	eventsRecord: (timestampUnixMs: number, level: EventLevel, category: EventCategory, message: string) => typedError<null, CmdError>(__TAURI_INVOKE("events_record", { timestampUnixMs, level, category, message })),
	// Most recent events (newest first).
	eventsRecent: (limit: number) => typedError<EventRecord[], CmdError>(__TAURI_INVOKE("events_recent", { limit })),
	// Filter by min-level + optional category, newest first.
	eventsFilter: (minLevel: EventLevel, category: "Wallet" | "Transaction" | "Network" | "Security" | "Ui" | "Other" | null, limit: number) => typedError<EventRecord[], CmdError>(__TAURI_INVOKE("events_filter", { minLevel, category, limit })),
	// Drop the entire event buffer.
	eventsClear: () => typedError<null, CmdError>(__TAURI_INVOKE("events_clear")),
	// Privacy-redacted snapshot for "Report a problem".
	eventsExportRedacted: () => typedError<EventRecord[], CmdError>(__TAURI_INVOKE("events_export_redacted")),
	// Read the active spend-limit policy.
	spendGetPolicy: () => typedError<SpendPolicy, CmdError>(__TAURI_INVOKE("spend_get_policy")),
	// Replace the spend-limit policy. Validates before persisting.
	spendSetPolicy: (policy: SpendPolicy) => typedError<null, CmdError>(__TAURI_INVOKE("spend_set_policy", { policy })),
	// Read the rolling daily-spend state.
	spendGetState: () => typedError<SpendState, CmdError>(__TAURI_INVOKE("spend_get_state")),
	/**
	 *  Evaluate a prospective tx against the active policy/state.
	 * 
	 *  Read-only: the returned `next_state` is what the host should
	 *  pass to `spend_commit` only after the tx is actually broadcast.
	 */
	spendEvaluate: (nowUnix: number, attemptUsd: number) => typedError<LimitEvaluation, CmdError>(__TAURI_INVOKE("spend_evaluate", { nowUnix, attemptUsd })),
	/**
	 *  Persist the `next_state` produced by `spend_evaluate` after a
	 *  successful broadcast.
	 */
	spendCommit: (nextState: SpendState) => typedError<null, CmdError>(__TAURI_INVOKE("spend_commit", { nextState })),
	// Reset the rolling spend state to zero (keeps the policy).
	spendReset: () => typedError<null, CmdError>(__TAURI_INVOKE("spend_reset")),
	// Probe a single chain's effective endpoint and return latency / status.
	networkHealth: (chainId: string) => typedError<NetworkHealth, CmdError>(__TAURI_INVOKE("network_health", { chainId })),
	// Probe every supported chain in parallel.
	networkHealthAll: () => typedError<NetworkHealth[], CmdError>(__TAURI_INVOKE("network_health_all")),
	// Inspect (without revealing) the user's 1inch configuration.
	getExchangeSettings: () => typedError<ExchangeSettings, CmdError>(__TAURI_INVOKE("get_exchange_settings")),
	// Persist 1inch credentials. Pass `null` (or empty) to clear a field.
	setExchangeSettings: (args: ExchangeConfigArgs) => typedError<ExchangeSettings, CmdError>(__TAURI_INVOKE("set_exchange_settings", { args })),
	/**
	 *  Quote an EVM swap via 1inch v6.
	 * 
	 *  `chain_id` is the EIP-155 chain id (1 = mainnet, 137 = polygon, …).
	 *  Token addresses use 1inch's convention: the native asset is
	 *  `0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee`.
	 */
	exchangeQuote: (chainId: number, src: string, dst: string, amount: string) => typedError<Quote, CmdError>(__TAURI_INVOKE("exchange_quote", { chainId, src, dst, amount })),
	/**
	 *  Execute an EVM swap via 1inch v6.
	 * 
	 *  For ERC-20 source tokens this command also handles the on-chain
	 *  allowance: if the router's allowance is below the requested amount,
	 *  Atlas signs and broadcasts an `approve` transaction first, then the
	 *  swap. Both transactions use the wallet's pending nonce — the swap is
	 *  expected to land in the block immediately after the approval.
	 */
	exchangeSwap: (args: ExchangeSwapArgs) => typedError<ExchangeSwapResult, CmdError>(__TAURI_INVOKE("exchange_swap", { args })),
	// Fetch a Jupiter v6 quote for a Solana swap.
	jupiterQuote: (args: JupiterQuoteArgs) => typedError<JupiterQuote, CmdError>(__TAURI_INVOKE("jupiter_quote", { args })),
	/**
	 *  Build an unsigned Jupiter swap transaction for the supplied
	 *  quote. Returns a base-64 encoded versioned transaction the
	 *  caller must sign with their Solana key and broadcast through
	 *  `atlas-chain-solana`.
	 */
	jupiterSwap: (args: JupiterSwapArgs) => typedError<SwapTransaction, CmdError>(__TAURI_INVOKE("jupiter_swap", { args })),
	/**
	 *  Fetch a THORChain swap quote. The returned `inbound_address`
	 *  + `memo` are what the wallet then sends to on the source
	 *  chain.
	 */
	thorchainQuote: (args: ThorchainQuoteArgs) => typedError<ThorchainQuote, CmdError>(__TAURI_INVOKE("thorchain_quote", { args })),
	// Read-only ChangeNOW estimate.
	changenowEstimate: (args: ChangeNowEstimateArgs) => typedError<Estimate, CmdError>(__TAURI_INVOKE("changenow_estimate", { args })),
	/**
	 *  Create a ChangeNOW exchange transaction. Returns the deposit
	 *  address the wallet must send the source asset to.
	 */
	changenowCreate: (args: ChangeNowCreateArgs) => typedError<CreatedExchange, CmdError>(__TAURI_INVOKE("changenow_create", { args })),
	/**
	 *  Return ranked quotes from every applicable provider. Failures
	 *  are surfaced as entries with `out_amount = None` and an
	 *  `error` message; they sort to the bottom.
	 */
	routeQuotes: (args: RouteQuotesArgs) => typedError<RoutedQuote[], CmdError>(__TAURI_INVOKE("route_quotes", { args })),
	listProfiles: () => typedError<ProfileSummary[], CmdError>(__TAURI_INVOKE("list_profiles")),
	activeProfile: () => typedError<{
	// Stable id (as string for JS).
	id: string,
	// Human-visible label.
	name: string,
	// `"hot"` or `"watch_only"`.
	kind: string,
	// Whether this profile can sign transactions.
	signing: boolean,
	// Creation timestamp.
	created_at: string,
	// Number of watched accounts (0 for hot profiles).
	watch_account_count: number,
} | null, CmdError>(__TAURI_INVOKE("active_profile")),
	/**
	 *  Returns how the active profile expects to sign transactions.
	 *  Frontend Send / Swap flows poll this on mount so they can
	 *  switch the confirm button between "Unlock to send",
	 *  "Confirm on device", and "Watch-only — cannot send".
	 */
	activeSigningCapability: () => typedError<SigningCapability, CmdError>(__TAURI_INVOKE("active_signing_capability")),
	switchProfile: (id: string) => typedError<null, CmdError>(__TAURI_INVOKE("switch_profile", { id })),
	renameProfile: (id: string, newName: string) => typedError<null, CmdError>(__TAURI_INVOKE("rename_profile", { id, newName })),
	deleteProfile: (id: string) => typedError<null, CmdError>(__TAURI_INVOKE("delete_profile", { id })),
	createWatchOnlyProfile: (args: CreateWatchOnlyArgs) => typedError<ProfileSummary, CmdError>(__TAURI_INVOKE("create_watch_only_profile", { args })),
	/**
	 *  Create a hardware-backed profile. Accounts are expected to have
	 *  already been derived from the device by the caller (via the
	 *  hardware-ledger / hardware-trezor crate); this command is the
	 *  pure persistence half.
	 */
	createHardwareProfile: (args: CreateHardwareArgs) => typedError<ProfileSummary, CmdError>(__TAURI_INVOKE("create_hardware_profile", { args })),
	/**
	 *  Return the most-recent cached transactions. Pass chain_id = "" to query
	 *  across every chain.
	 */
	txHistoryList: (chainId: string, limit: number) => typedError<TxRecord[], CmdError>(__TAURI_INVOKE("tx_history_list", { chainId, limit })),
	/**
	 *  Update the on-disk status of a single tx (pending ? confirmed/failed).
	 *  The frontend can call this once a confirmation watcher resolves.
	 */
	txHistorySetStatus: (chainId: string, txid: string, status: string) => typedError<null, CmdError>(__TAURI_INVOKE("tx_history_set_status", { chainId, txid, status })),
	/**
	 *  Allow the UI to record a tx that didn't go through Atlas's send flow
	 *  (e.g. an external broadcast the user wants to track).
	 */
	txHistoryRecord: (record: TxRecord) => typedError<null, CmdError>(__TAURI_INVOKE("tx_history_record", { record })),
	/**
	 *  Add (or replace) an encrypted address-book entry. Requires the
	 *  wallet to be unlocked because the encryption key is derived from
	 *  the BIP-39 seed.
	 */
	addressBookPut: (chainId: string, address: string, label: string, notes: string | null) => typedError<null, CmdError>(__TAURI_INVOKE("address_book_put", { chainId, address, label, notes })),
	/**
	 *  List address-book entries (decrypted) for `chain_id`. Pass an empty
	 *  string to list across every chain. Requires the wallet to be
	 *  unlocked.
	 */
	addressBookList: (chainId: string) => typedError<AddressBookEntry[], CmdError>(__TAURI_INVOKE("address_book_list", { chainId })),
	/**
	 *  Remove one address-book entry. Returns `true` if a row was deleted.
	 *  Does NOT require the wallet to be unlocked — the row identifiers
	 *  (chain_id, address) are stored as plaintext.
	 */
	addressBookRemove: (chainId: string, address: string) => typedError<boolean, CmdError>(__TAURI_INVOKE("address_book_remove", { chainId, address })),
	// Atlas EVM chain ids for which the NFT viewer can fetch data.
	nftSupportedChains: () => typedError<string[], CmdError>(__TAURI_INVOKE("nft_supported_chains")),
	/**
	 *  Fetch NFTs that `address` owns on `chain_id`. `chain_id` must be
	 *  one of [`nft_supported_chains`]. Read-only — never signs or
	 *  transfers anything.
	 */
	nftListOwned: (chainId: string, address: string) => typedError<OwnedNft[], CmdError>(__TAURI_INVOKE("nft_list_owned", { chainId, address })),
};

/** Events */
export const events = {
	balanceUpdatedEvent: makeEvent<BalanceUpdatedEvent>("balance-updated-event"),
	txRecordedEvent: makeEvent<TxRecordedEvent>("tx-recorded-event"),
	txStatusChangedEvent: makeEvent<TxStatusChangedEvent>("tx-status-changed-event"),
	walletLockedEvent: makeEvent<WalletLockedEvent>("wallet-locked-event"),
};

/* Types */
// Accounting method for matching sells against buys.
export type AccountingMethod = "Fifo" | "Lifo" | "AverageCost";

// One decrypted address-book entry as the UI sees it.
export type AddressBookEntry = {
	// Atlas chain id (`"eth"`, `"btc"`, …).
	chain_id: string,
	// Public address (plaintext).
	address: string,
	// User-supplied display label (decrypted).
	label: string,
	// Optional notes (decrypted).
	notes: string | null,
	// Unix timestamp (seconds) when the entry was added.
	created_at: number,
};

// Output of `aggregate_prices`.
export type AggregatedPrice = {
	// Median of the surviving quotes.
	price: number,
	// Sources whose quote was within tolerance.
	accepted: SourceQuote[],
	// Sources rejected as outliers.
	rejected: SourceQuote[],
	/**
	 *  Median absolute deviation from the *initial* median, in bps,
	 *  across all input quotes (volatility hint for the UI).
	 */
	spread_bps: number,
};

/**
 *  A precise on-chain amount: integer base units + asset metadata.
 * 
 *  `value` is denominated in the asset's smallest unit (sat for BTC,
 *  wei for ETH). We use `u128` as a JSON-friendly carrier for any
 *  realistic balance.
 */
export type Amount = {
	// Integer value in base units.
	value: number,
	// Asset this amount denominates.
	asset: Asset,
};

// One outstanding approval as seen on-chain.
export type Approval = {
	chain_id: string,
	token_address: string,
	token_symbol: string,
	// Decimal places (use 0 for ERC-721 / `ForAll`).
	token_decimals: number,
	spender_address: string,
	// Optional curated label — `None` if the spender is unknown.
	spender_label: string | null,
	/**
	 *  Decimal-string allowance in base units. For `ForAll` this is
	 *  the literal string `"unlimited"`. For ERC-721 single-token
	 *  approvals this is the token id.
	 */
	allowance: string,
	kind: ApprovalKind,
	// Unix seconds — when the approval was first observed.
	first_seen: number,
	/**
	 *  Unix seconds — when the spender last moved tokens via this
	 *  approval. `None` if never used.
	 */
	last_used: number | null,
};

// Tunables. Defaults are conservative.
export type ApprovalConfig = {
	// Spenders flagged as known-malicious (lower-cased addresses).
	blocklist: string[],
	/**
	 *  Spenders that are well-known dApps (lower-cased addresses).
	 *  These cap their risk at `High` (unlimited) or `Medium` (finite).
	 */
	allowlist: string[],
	/**
	 *  "Unlimited" allowance threshold in base units. Approvals above
	 *  this are considered effectively unlimited even if numerically
	 *  finite. Default: `2^200` ≈ 1.6e60.
	 */
	unlimited_threshold: string,
	/**
	 *  Approvals last used (or first-seen) longer than this many
	 *  seconds ago are considered stale and bumped one tier up.
	 */
	stale_after_secs: number,
};

// Asset standard for an approval.
export type ApprovalKind = 
// `approve(spender, amount)` on an ERC-20.
"Erc20" | 
// `approve(spender, tokenId)` on an ERC-721.
"Erc721" | 
// `setApprovalForAll(spender, true)` (works for both 721 and 1155).
"ForAll";

/**
 *  One row in the revoke queue. Keeps the original `Approval` plus
 *  the computed risk tier and a short human-readable rationale.
 */
export type ApprovalRisk = {
	approval: Approval,
	level: RiskLevel,
	reasons: string[],
};

// Per-chain summary for the dashboard header.
export type ApprovalSummary = {
	chain_id: string,
	total: number,
	critical: number,
	high: number,
	medium: number,
	low: number,
	unique_spenders: number,
};

// A cryptocurrency asset (native or token).
export type Asset = {
	// Stable identifier — usually the lowercase ticker (`btc`, `eth`, `usdc`).
	id: string,
	// Display ticker, e.g. `BTC`.
	symbol: string,
	// Decimals (8 for BTC, 18 for ETH, 6 for USDC, …).
	decimals: number,
	// Optional logo URL/hint for the UI.
	logo: string | null,
};

// Per-asset summary row.
export type AssetTotals = {
	asset: string,
	// Sum of `amount` across send rows.
	sent: string,
	// Sum of `amount` across receive rows.
	received: string,
	// `received - sent` (may be negative; signed decimal string).
	net: string,
	send_count: number,
	receive_count: number,
};

/**
 *  Emitted when a balance refresh observes a different value than what the
 *  frontend last queried. Reserved for the upcoming background watcher —
 *  kept in the schema now so listening UI code is forward-compatible.
 */
export type BalanceUpdatedEvent = {
	chain_id: string,
	address: string,
	// Base-units integer encoded as a decimal string for u128 safety.
	amount: string,
	asset: string,
};

/**
 *  Snapshot of biometric capabilities + user preference. Used by
 *  the unlock screen to decide whether to show the Hello / Touch
 *  ID prompt button.
 */
export type BiometricStatus = {
	// `true` if the OS reports an enrolled sensor reachable.
	available: boolean,
	// `true` if the user has opted in to biometric unlock.
	enabled: boolean,
};

export type BitcoinPayment = {
	address: string,
	// Amount in BTC as a decimal string (preserves precision).
	amount_btc: string | null,
	label: string | null,
	message: string | null,
};

// What kind of bad-actor an entry is.
export type BlocklistCategory = 
// Wallet drainer (auto-sweeps approved tokens).
"Drainer" | 
// Phishing / impersonation wallet.
"Phishing" | 
// Generic scam / pig-butchering / fake support.
"Scam" | 
// OFAC or other government sanctions list.
"Sanctioned" | 
// Reported by the user themselves.
"UserReported";

// One row in the blocklist.
export type BlocklistEntry = {
	// Normalised address (lower-case, stripped `0x`).
	address: string,
	category: BlocklistCategory,
	// Free-text source attribution (e.g. "scamsniffer", "user").
	source: string,
	// Optional reason / context.
	note: string | null,
	// Unix seconds when added.
	added_at: number,
};

// Result of looking up an address.
export type BlocklistVerdict = { kind: "Clean" } | { kind: "Listed"; data: BlocklistEntry };

export type Chain = "Bitcoin" | "Ethereum";

// Aggregated staking position for one chain.
export type ChainPosition = {
	chain: StakingChain,
	delegations: Delegation[],
	total_staked: number,
	total_pending_rewards: number,
	total_unbonding: number,
	/**
	 *  Stake-weighted average net APR across the user's delegations.
	 *  0.0 if `total_staked == 0`.
	 */
	weighted_net_apr: number,
};

export type ChainSummary = {
	id: string,
	display_name: string,
	symbol: string,
	decimals: number,
	family: string,
	enabled_by_default: boolean,
};

// Per-chain summary row.
export type ChainTotals = {
	chain_id: string,
	tx_count: number,
	send_count: number,
	receive_count: number,
	pending_count: number,
	failed_count: number,
};

export type ChangeNowCreateArgs = {
	// Source ticker.
	from_currency: string,
	// Destination ticker.
	to_currency: string,
	// Optional source-network override.
	from_network: string | null,
	// Optional destination-network override.
	to_network: string | null,
	// Source amount (decimal string, display unit).
	from_amount: string,
	// User's destination address.
	address: string,
	// Optional memo / destination tag (XRP, XLM, ...).
	extra_id: string | null,
	// Optional refund address.
	refund_address: string | null,
	// "standard" or "fixed-rate".
	flow: string,
	// rateId from a fixed-rate estimate. Required for fixed-rate.
	rate_id: string | null,
	// ChangeNOW partner-program API key. Required.
	api_key: string,
};

export type ChangeNowEstimateArgs = {
	// Source ticker, lowercase (e.g. "btc").
	from_currency: string,
	// Destination ticker.
	to_currency: string,
	// Optional source-network override (USDT etc.).
	from_network: string | null,
	// Optional destination-network override.
	to_network: string | null,
	// Source amount as a decimal string in display units.
	from_amount: string,
	// "standard" (floating rate) or "fixed-rate".
	flow: string,
};

export type CmdError = { kind: "NotInitialized"; message: string } | { kind: "Locked" } | 
/**
 *  Active profile is hardware-backed; the frontend must route
 *  the operation through the connected device rather than
 *  asking for a password. Carries the vendor name (`"ledger"`
 *  / `"trezor"`) so the UI can pick the right driver.
 */
{ kind: "HardwareSignatureRequired"; message: string } | { kind: "InvalidInput"; message: string } | { kind: "Wallet"; message: string } | { kind: "Chain"; message: string } | { kind: "Io"; message: string } | { kind: "Profile"; message: string };

/**
 *  Wire format Atlas exchanges with a co-signer wallet (Sparrow,
 *  Specter, another Atlas instance).
 */
export type CoSignerInvite = {
	// Wire-format version. Bump if the field set changes.
	v: number,
	// The co-signer's xpub + origin + fingerprint.
	signer: MultisigSigner,
	// Optional human label ("Alice's Coldcard").
	label: string | null,
	// Optional policy hint ("2-of-3", "treasury cold storage").
	policy_hint: string | null,
};

// One collection grouping in the gallery.
export type CollectionGroup = {
	// `chain:contract` — stable cross-chain key.
	key: string,
	chain_id: string,
	contract: string,
	// Display name (falls back to the contract address when absent).
	name: string,
	item_count: number,
	/**
	 *  Sum of per-item `floor_usd` values that were known. Items with
	 *  unknown floor are excluded from the sum and recorded in
	 *  `unpriced_count`.
	 */
	estimated_value_usd: number,
	unpriced_count: number,
	// Cover image: the first item's image, if any.
	cover_image: string | null,
	// Items in stable order (by token-id string).
	items: OwnedNft[],
};

export type Contact = {
	id: string,
	name: string,
	note: string,
	addresses: ContactAddress[],
};

export type ContactAddress = {
	chain: ContactChain,
	// Lower-cased, trimmed.
	address: string,
};

export type ContactChain = "Bitcoin" | "Ethereum";

export type CreateHardwareArgs = {
	name: string,
	vendor: HardwareVendor,
	accounts: HwAccount[],
};

export type CreateWalletArgs = {
	password: string,
	word_count: number,
	/**
	 *  Optional human-friendly profile name. Defaults to `"Default"` for the
	 *  first wallet, otherwise required.
	 */
	name?: string | null,
};

export type CreateWatchOnlyArgs = {
	name: string,
	accounts: WatchAccount[],
};

/**
 *  Created-exchange response: contains the deposit address the
 *  wallet must send the source asset to.
 */
export type CreatedExchange = {
	// ChangeNOW transaction id (used to poll status later).
	id: string,
	// Deposit address on the source chain.
	payinAddress: string,
	// Optional deposit memo / destination tag.
	payinExtraId?: string | null,
	// Echoed payout address.
	payoutAddress: string,
	// Echoed source ticker.
	fromCurrency: string,
	// Echoed destination ticker.
	toCurrency: string,
	// Source amount actually expected (decimal string, display).
	fromAmount?: string | null,
	// Estimated destination amount.
	toAmount?: string | null,
	// Echoed flow.
	flow: string,
};

/**
 *  One user-imported token row. Mirrors `OwnedTokenMeta` minus the
 *  derived `id` / `source` (which are always `"custom"` here).
 */
export type CustomToken = {
	// Atlas chain id (`"eth"`, `"polygon"`, …).
	chain_id: string,
	/**
	 *  Contract address (case-preserved as the user typed it; lookups
	 *  should compare case-insensitively).
	 */
	contract: string,
	// On-chain ticker.
	symbol: string,
	// Display name.
	display_name: string,
	// Decimals (0–38).
	decimals: number,
	// `"erc-20"` or `"trc-20"`.
	standard: string,
	// Optional logo URL.
	logo_uri: string | null,
};

// Outcome of evaluating a candidate URL.
export type DappAssessment = {
	// The normalised origin (`scheme://host[:port]`) that was checked.
	origin: string,
	risk: DappRisk,
	// Matched curated entry, if any.
	entry: DappEntry | null,
	// Human-readable warnings shown in the consent UI.
	warnings: string[],
	/**
	 *  Stable per-origin fingerprint useful as a cache key in the UI
	 *  (first 16 hex chars of `sha256(origin)`).
	 */
	fingerprint: string,
};

// Category tag used purely for UI grouping.
export type DappCategory = "defi" | "nft" | "bridge" | "game" | "social" | "other";

// One curated dApp.
export type DappEntry = {
	name: string,
	/**
	 *  Canonical homepage origin, e.g. `https://app.uniswap.org`.
	 *  Stored already-normalised (no trailing slash, lowercased host).
	 */
	origin: string,
	category: DappCategory,
	// Optional comma-separated tags ("amm", "lending", ...).
	tags: string[],
};

// Risk verdict returned to the UI.
export type DappRisk = 
// Origin matches a curated, audited entry.
"verified" | 
// Origin is unknown to the registry — proceed with caution.
"unknown" | 
// Origin is on the blocklist (phishing / known scam).
"blocked";

// Result of decoding one tx.
export type DecodedCall = 
// Empty calldata (plain native-asset transfer).
{ tag: "NativeTransfer" } | 
// `transfer(address recipient, uint256 amount)`.
{ tag: "Erc20Transfer"; recipient: string; amount: string } | 
// `transferFrom(address from, address to, uint256 amount)`.
{ tag: "Erc20TransferFrom"; from: string; to: string; amount: string } | 
// `approve(address spender, uint256 amount)`.
{ tag: "Erc20Approve"; spender: string; amount: string; unlimited: boolean } | 
// `increaseAllowance(address spender, uint256 added)`.
{ tag: "Erc20IncreaseAllowance"; spender: string; added: string } | 
// `decreaseAllowance(address spender, uint256 subtracted)`.
{ tag: "Erc20DecreaseAllowance"; spender: string; subtracted: string } | 
// `safeTransferFrom(address from, address to, uint256 idOrAmt)`.
{ tag: "NftSafeTransferFrom"; from: string; to: string; token_id: string } | 
// `setApprovalForAll(address operator, bool approved)`.
{ tag: "NftSetApprovalForAll"; operator: string; approved: boolean } | 
// `deposit()` on a wrapped-native (e.g. WETH9).
{ tag: "WrapDeposit" } | 
// `withdraw(uint256)` on a wrapped-native.
{ tag: "WrapWithdraw"; amount: string } | 
// `multicall(bytes[])` (Uniswap V3 / Aggregator style).
{ tag: "Multicall"; inner_count: number } | 
// Selector did not match any known shape.
{ tag: "Unknown"; selector: string };

// User's delegation to one validator.
export type Delegation = {
	chain: StakingChain,
	validator_id: string,
	// Delegated amount in base units.
	amount: number,
	/**
	 *  Pending rewards in base units. May be 0 for chains that
	 *  auto-restake (Lido stETH).
	 */
	pending_rewards: number,
	// Pending unbonding amount in base units (still locked).
	unbonding: number,
};

export type DiversificationBand = "Diversified" | "Balanced" | "Concentrated" | "HighlyConcentrated";

export type DiversificationReport = {
	total_usd: number,
	position_count: number,
	// 0..=10000, single-asset = 10000.
	hhi: number,
	band: DiversificationBand,
	largest_share: number,
	positions: PositionWeight[],
};

// EIP-1559 fee suggestion (all in wei).
export type Eip1559Suggestion = {
	tier: FeeTier,
	max_priority_fee_per_gas: number,
	max_fee_per_gas: number,
};

// Output of `eip1559_suggest`.
export type Eip1559Suggestions = {
	slow: Eip1559Suggestion,
	standard: Eip1559Suggestion,
	fast: Eip1559Suggestion,
};

// What the signing request authorises.
export type Eip712Category = 
// ERC-2612 token spend approval.
"Permit" | 
// Uniswap Permit2 single / batch approval.
"Permit2" | 
// OpenSea Seaport order signature (NFT listing).
"SeaportOrder" | 
// Gnosis Safe multisig transaction.
"SafeTx" | 
// Anything else.
"Generic";

// EIP-712 domain separator fields, only the parts we surface.
export type Eip712Domain = {
	name: string | null,
	version: string | null,
	chain_id: number | null,
	verifying_contract: string | null,
};

// Inspector output.
export type Eip712Report = {
	primary_type: string,
	domain: Eip712Domain,
	category: Eip712Category,
	risk: SignatureRisk,
	findings: string[],
};

// Subset of the estimate response.
export type Estimate = {
	// Echoed source ticker.
	fromCurrency: string,
	// Echoed destination ticker.
	toCurrency: string,
	/**
	 *  Estimated destination amount (decimal string, display
	 *  unit). May be missing if amount is below the protocol
	 *  minimum, in which case `min_amount` will be set.
	 */
	toAmount?: string | null,
	// Echoed flow (`"standard"` / `"fixed-rate"`).
	flow: string,
	/**
	 *  Indicative network fee (decimal string, destination
	 *  asset, display unit).
	 */
	networkFee?: string | null,
	// Minimum source amount accepted on this pair.
	minAmount?: string | null,
	// Maximum source amount accepted on this pair.
	maxAmount?: string | null,
	/**
	 *  Quote / rate id (only for fixed-rate flow). Required when
	 *  later creating a fixed-rate exchange.
	 */
	rateId?: string | null,
};

export type EthereumPayment = {
	// `to` for native, or the contract for `transfer`.
	address: string,
	chain_id: number | null,
	/**
	 *  `Some` only when a `transfer` function call is encoded
	 *  (ERC-20 token transfers).
	 */
	function: string | null,
	/**
	 *  For ERC-20: real recipient (decoded from `address` query
	 *  parameter on the contract call).
	 */
	token_recipient: string | null,
	/**
	 *  Amount in wei as a decimal string. For ERC-20 this is the
	 *  `uint256` parameter (token base units).
	 */
	amount_wei: string | null,
	// Optional gas / gasPrice query params, unparsed.
	gas: string | null,
};

export type EventCategory = "Wallet" | "Transaction" | "Network" | "Security" | "Ui" | "Other";

export type EventLevel = "Debug" | "Info" | "Warn" | "Error";

export type EventRecord = {
	timestamp_unix_ms: number,
	level: EventLevel,
	category: EventCategory,
	message: string,
};

export type ExchangeConfigArgs = {
	api_key: string | null,
	base_url: string | null,
};

export type ExchangeSettings = {
	api_key_set: boolean,
	base_url: string,
};

export type ExchangeSwapArgs = {
	chain_id: number,
	src: string,
	dst: string,
	// Source amount, base units, decimal string.
	amount: string,
	// Maximum slippage in basis points (100 = 1%).
	slippage_bps: number,
	// `slow|normal|fast` or a raw decimal wei gas-price.
	fee_level: string,
};

export type ExchangeSwapResult = {
	// Final swap transaction hash.
	txid: string,
	// If a pre-approve was needed (ERC-20 source), this is its tx hash.
	approve_txid: string | null,
	// Estimated destination amount, base units, decimal string.
	to_amount: string,
};

// Three canonical fee tiers presented to the user.
export type FeeOption = {
	// `"slow" | "normal" | "fast"`.
	level: string,
	// Estimated fee for a typical transaction.
	estimated_fee: Amount,
	// Estimated time-to-confirm in seconds.
	eta_seconds: number,
	// Implementation-defined hint payload (e.g. sat/vB or gas price), JSON-encoded as string for FFI simplicity.
	raw_hint: string,
};

// Speed tier the user picked.
export type FeeTier = "Slow" | "Standard" | "Fast";

// Filter knobs passed in from the UI.
export type GalleryFilter = {
	/**
	 *  If true, items matching the spam heuristic are routed to
	 *  `hidden_items` instead of being grouped.
	 */
	hide_spam: boolean,
	/**
	 *  Hide collections worth less than this in USD (estimated). 0
	 *  disables the filter.
	 */
	min_collection_value_usd: number,
	// If non-empty, only items on these chains are included.
	chains: string[],
};

// Aggregated view of a user's NFT holdings.
export type GalleryView = {
	/**
	 *  Visible collections, sorted by estimated USD value desc, then
	 *  by item count desc, then by name.
	 */
	collections: CollectionGroup[],
	/**
	 *  Items the spam filter set aside. Surfaced so the user can
	 *  un-hide them from settings.
	 */
	hidden_items: OwnedNft[],
	total_collections: number,
	total_items: number,
	total_value_usd: number,
};

export type GasCost = {
	/**
	 *  Total wei the network will charge:
	 *  `gas_used * effective_gas_price_wei`.
	 */
	wei: number,
	// `wei` formatted as a native-token amount, e.g. "0.001234".
	native_amount: string,
	// USD value to 4 decimals, e.g. "2.4321".
	usd: string,
};

/**
 *  Recognised hardware-wallet vendors. Stored verbatim in the
 *  profile blob so the registry survives Atlas upgrades that add
 *  or remove vendors.
 */
export type HardwareVendor = 
// Ledger Nano S / S+ / X.
"ledger" | 
// Trezor One / Model T / Safe 3 / Safe 5.
"trezor";

// Filter knobs from the UI.
export type HistoryFilter = {
	// If non-empty, only txs on these chains are kept.
	chains: string[],
	// If set, only txs with this direction (`"send"` / `"receive"`).
	direction: string | null,
	// If non-empty, only txs in these statuses.
	statuses: string[],
	// Inclusive lower bound on timestamp.
	since: number | null,
	// Inclusive upper bound on timestamp.
	until: number | null,
	/**
	 *  Free-text query, matched (case-insensitively) against txid,
	 *  counterparty, asset, and memo.
	 */
	query: string | null,
	// If set, only txs for this asset ticker (case-insensitive).
	asset: string | null,
};

// Result of running `summarise`.
export type HistorySummary = {
	total_count: number,
	by_asset: AssetTotals[],
	by_chain: ChainTotals[],
	// First and last txs (by timestamp) in the filtered range.
	first_timestamp: number | null,
	last_timestamp: number | null,
};

export type Holding = {
	symbol: string,
	usd_value: number,
};

/**
 *  One account exported from a hardware wallet. The `xpub` is
 *  optional because some chain apps return an address but not a
 *  chain code (Solana, Cosmos). When we have an xpub we can derive
 *  further child addresses without reconnecting the device.
 */
export type HwAccount = {
	// Chain identifier this account belongs to.
	chain_id: string,
	// Public address shown to the user.
	address: string,
	// BIP-32 derivation path string (`"m/44'/60'/0'/0/0"`).
	derivation_path: string,
	// Extended public key, if the device returned one.
	xpub?: string | null,
	// Optional human label.
	label?: string | null,
};

export type ImportWalletArgs = {
	password: string,
	phrase: string,
	passphrase?: string | null,
	name?: string | null,
};

// One incoming transfer the user received.
export type IncomingTransfer = {
	txid: string,
	from: string,
	// Decimal-string amount in base units. Empty / "0" treated as zero.
	amount: string,
	// Unix seconds.
	timestamp: number,
	asset: string,
};

/**
 *  Subset of the Jupiter `/quote` response that Atlas consumes.
 *  Jupiter's actual schema is wider; we keep only the fields the
 *  UI needs, so adding new ones doesn't ripple through the
 *  frontend.
 */
export type JupiterQuote = {
	// Echoed input mint.
	inputMint: string,
	// Echoed output mint.
	outputMint: string,
	// Echoed input amount in base units.
	inAmount: string,
	// Expected output amount in base units.
	outAmount: string,
	// Worst-case output amount after slippage, in base units.
	otherAmountThreshold: string,
	/**
	 *  Total price impact across the route, as a string-encoded
	 *  decimal in `[0, 1]` (e.g. `"0.0034"` for 0.34 %).
	 */
	priceImpactPct: string,
	// Echoed slippage (Jupiter may round down).
	slippageBps: number,
	/**
	 *  Raw route plan, kept opaque so we can pass it back to
	 *  `/swap` verbatim. Jupiter's plan structure changes
	 *  occasionally; treating it as `Value` insulates us. The
	 *  frontend never inspects it, so we surface it as a JSON
	 *  string in the typescript bindings.
	 */
	routePlan: string,
};

export type JupiterQuoteArgs = {
	/**
	 *  SPL mint address of the input token (use the wrapped-SOL
	 *  mint for native SOL).
	 */
	input_mint: string,
	// SPL mint address of the output token.
	output_mint: string,
	// Amount in input-mint base units (string-encoded u64).
	amount: string,
	// Slippage in basis points (100 = 1%). Capped at 5000.
	slippage_bps: number,
	// Optional Atlas platform fee in basis points (max 50).
	platform_fee_bps: number | null,
};

export type JupiterSwapArgs = {
	// Quote returned by `jupiter_quote`.
	quote: JupiterQuote,
	/**
	 *  Solana base-58 public key of the wallet paying for the
	 *  swap. The frontend pulls this from `get_address`.
	 */
	user_public_key: string,
	/**
	 *  Wrap / unwrap SOL automatically when the input or output
	 *  is the wrapped-SOL mint. Almost always `true` for end
	 *  users.
	 */
	wrap_and_unwrap_sol: boolean,
	/**
	 *  Optional Atlas referral fee account (SPL token account
	 *  of Atlas's referral PDA on the output mint).
	 */
	fee_account: string | null,
};

export type LimitDecision = "Allowed" | "RequiresConfirmation" | "Blocked";

export type LimitEvaluation = {
	decision: LimitDecision,
	/**
	 *  Reason text the UI can show: "Daily cap exceeded", etc.
	 *  Empty when `Allowed`.
	 */
	reason: ReasonCode,
	/**
	 *  State to persist *if* the tx goes through. Already includes
	 *  the rolled-over window and the new spend.
	 */
	next_state: SpendState,
	// USD remaining in the day after this tx. Saturating at 0.
	remaining_after_usd: number,
};

// One trusted address that closely resembles a candidate.
export type MimicMatch = {
	// The user's trusted address that the candidate mimics.
	trusted_address: string,
	// Number of leading hex characters that match.
	matching_prefix: number,
	// Number of trailing hex characters that match.
	matching_suffix: number,
};

export type MoonPayBuyArgs = {
	currency_code: string,
	wallet_address: string,
	base_currency_amount: string | null,
	base_currency_code: string | null,
	redirect_url: string | null,
};

/**
 *  MoonPay configuration surfaced to the UI. The secret key, when set,
 *  is reported only as a boolean — it never crosses the IPC boundary.
 */
export type MoonPayConfig = {
	api_key: string | null,
	secret_key_set: boolean,
	production: boolean,
};

export type MoonPayConfigInput = {
	api_key: string | null,
	// `Some("")` explicitly clears the stored secret. `None` leaves it as-is.
	secret_key: string | null,
	production: boolean,
};

export type MoonPaySellArgs = {
	base_currency_code: string,
	refund_wallet_address: string,
	base_currency_amount: string | null,
	quote_currency_code: string | null,
	redirect_url: string | null,
};

/**
 *  `threshold`-of-`signers` policy. Atlas refuses to construct a wallet
 *  with `threshold == 0`, `threshold > signers.len()`, or a signer set
 *  containing fewer than two parties — those are footguns, not policies.
 */
export type MultisigPolicy = {
	threshold: number,
	signers: MultisigSigner[],
	// `Mainnet` for production funds, `Testnet` for everything else.
	network: NetworkChoice,
};

/**
 *  A single signer in the multisig policy. `key_origin` ties the xpub
 *  back to its master key fingerprint and derivation path so a hardware
 *  wallet can later prove ownership before signing.
 */
export type MultisigSigner = {
	// 8-character hex master fingerprint (e.g. `"d34db33f"`).
	fingerprint: string,
	/**
	 *  Origin path — typically `m/48'/0'/0'/2'` for a BIP-48 P2WSH
	 *  account on mainnet.
	 */
	origin: string,
	// Account-level extended public key (`xpub.../zpub.../...`).
	xpub: string,
};

/**
 *  Compiled descriptor + the policy it came from. Atlas stores the
 *  descriptor string verbatim so a recovery from another wallet (Sparrow,
 *  Specter) is a simple paste.
 */
export type MultisigWallet = {
	policy: MultisigPolicy,
	/**
	 *  `wsh(sortedmulti(...))` descriptor string with `/<0;1>/*` ranged
	 *  suffix — the standard BIP-389 form for receive + change.
	 */
	descriptor: string,
};

export type NetworkChoice = "mainnet" | "testnet";

// Result of a single `network_health` probe.
export type NetworkHealth = {
	// Chain id this report describes (`"btc"`, `"eth"`, …).
	chain_id: string,
	// Effective endpoint URL we probed.
	endpoint: string,
	// Whether the endpoint URL is the user's override (`true`) or built-in default.
	is_user_override: boolean,
	// Number of samples sent.
	samples: number,
	// Number of samples that returned successfully.
	successes: number,
	// Median latency across successful samples, in milliseconds.
	latency_p50_ms: number | null,
	// 95th percentile latency across successful samples, in milliseconds.
	latency_p95_ms: number | null,
	// Most recently observed head height (block / slot number).
	head_height: number | null,
	// Bucketed status for the UI.
	status: NetworkStatus,
};

// Per-chain status bucket surfaced to the UI as a green / amber / red dot.
export type NetworkStatus = 
// Endpoint is reachable and responsive.
"synced" | 
// Endpoint responds but is slow or losing samples.
"lagging" | 
// All samples failed.
"offline";

/**
 *  Safe `Operation` enum — `Call` is the default, `DelegateCall` is
 *  reserved for module / library invocations and is *dangerous* on a
 *  generic Safe.
 */
export type Operation = "call" | "delegatecall";

/**
 *  One NFT a user owns. Mirrors the subset of Reservoir's
 *  `/users/{user}/tokens/v6` payload that the UI actually renders.
 */
export type OwnedNft = {
	// Atlas chain id this NFT lives on.
	chain_id: string,
	// EVM contract address (checksum or lowercase).
	contract: string,
	// Token id as a decimal string (NFTs are u256).
	token_id: string,
	// Optional human-readable name (`"BAYC #1234"`).
	name: string | null,
	// Collection display name.
	collection: string | null,
	/**
	 *  Best-effort image URI (already gateway-rewritten by
	 *  Reservoir when possible).
	 */
	image: string | null,
	/**
	 *  Most recent floor-ask price in USD. Watch-only — no
	 *  guarantee the NFT can actually be sold for this.
	 */
	floor_usd: number | null,
};

/**
 *  Owned counterpart of [`TokenMeta`] used for tokens fetched at runtime
 *  from tokenlists.org or imported manually by the user.
 * 
 *  Static + remote tokens unify behind this type at the IPC boundary so
 *  the UI can display both kinds without caring where they came from.
 */
export type OwnedTokenMeta = {
	/**
	 *  Stable identifier — for remote tokens this is `chain_id-contract`
	 *  in lowercase so duplicates dedupe naturally.
	 */
	id: string,
	// On-chain symbol.
	symbol: string,
	// Display name.
	display_name: string,
	// Atlas chain id (`"eth"`, `"polygon"`, …).
	chain_id: string,
	// Hex (EIP-55) or base58 contract address.
	contract: string,
	// On-chain decimals.
	decimals: number,
	// Token standard.
	standard: TokenStandard,
	// Optional logo URL (only present on remote tokens).
	logo_uri: string | null,
	// `"static"`, `"remote"` (tokenlists.org), or `"custom"` (user-added).
	source: string,
};

// Discriminated payment intent.
export type PaymentIntent = { kind: "Bitcoin" } & (BitcoinPayment) | { kind: "Ethereum" } & (EthereumPayment);

// Configuration for `analyze`.
export type PhishingConfig = {
	// Curated allowlist (etld+1, lower-case). Always returns Safe.
	allowlist: string[],
	// Hard blocklist (etld+1, lower-case). Always returns Phish.
	blocklist: string[],
	/**
	 *  Targets to typosquat-check against. e.g. `["uniswap.org",
	 *  "aave.com", "opensea.io"]`. Lower-case, no scheme.
	 */
	targets: string[],
};

// Result of one analysis.
export type PhishingReport = {
	host: string,
	verdict: PhishingVerdict,
	reasons: string[],
	// Closest target from `targets` and the edit distance found.
	closest_target: string | null,
	closest_distance: number | null,
};

// Verdict tier for a single origin.
export type PhishingVerdict = 
// Origin is on the curated allowlist or shows no red flags.
"Safe" | 
// One or two soft signals; UI should warn but not block.
"Suspicious" | 
// Strong indicators (Punycode + typosquat / etc.) — block.
"Phish";

// One flagged transfer.
export type PoisonAlert = {
	transfer: IncomingTransfer,
	// The trusted counterparty whose address is being mimicked.
	mimicked: TrustedCounterparty,
	// Number of leading hex characters that match.
	matching_prefix: number,
	// Number of trailing hex characters that match.
	matching_suffix: number,
	// True if amount ≤ `dust_threshold`.
	is_dust: boolean,
};

// Knobs for the detector.
export type PoisonConfig = {
	/**
	 *  Minimum number of leading hex characters that must match for
	 *  a transfer to be flagged. Default: 6.
	 */
	min_prefix: number,
	/**
	 *  Minimum number of trailing hex characters that must match.
	 *  Default: 6.
	 */
	min_suffix: number,
	/**
	 *  Decimal-string upper bound on "dust" amount (inclusive).
	 *  Transfers <= this in base units are extra-suspect. Default
	 *  `"1000000"` — 1e6 base units (≈ 1 USDC, ≈ 1e-12 ETH).
	 */
	dust_threshold: string,
};

// Aggregate report.
export type PortfolioReport = {
	positions: Position[],
	realized: RealizedEvent[],
	total_realized_usd: number,
	total_unrealized_usd: number,
};

// Output: one row per asset still held.
export type Position = {
	asset: string,
	quantity_held: number,
	cost_basis_usd: number,
	market_value_usd: number,
	unrealized_pnl_usd: number,
};

export type PositionWeight = {
	symbol: string,
	usd_value: number,
	// Weight as a fraction of the total, 0..=1.
	weight: number,
};

// A single cached price observation.
export type PricePoint = {
	// Price in the requested fiat currency.
	price: number,
	// 24h change as a percentage.
	change_24h: number,
};

// Frontend-friendly summary of a profile.
export type ProfileSummary = {
	// Stable id (as string for JS).
	id: string,
	// Human-visible label.
	name: string,
	// `"hot"` or `"watch_only"`.
	kind: string,
	// Whether this profile can sign transactions.
	signing: boolean,
	// Creation timestamp.
	created_at: string,
	// Number of watched accounts (0 for hot profiles).
	watch_account_count: number,
};

export type PsbtInputSummary = {
	// Number of partial signatures already collected for this input.
	partial_sigs: number,
	// Value of the spent output, when known.
	value_sats: number | null,
};

export type PsbtOutputSummary = {
	value_sats: number,
	/**
	 *  Best-effort decoded address (mainnet first, then testnet). `None`
	 *  if the script doesn't map to a standard address.
	 */
	address: string | null,
};

/**
 *  Lightweight summary of a PSBT for the UI: which inputs are signed
 *  and how many signatures each carries, plus the per-output amount /
 *  address. Avoids shipping the entire raw byte blob across IPC every
 *  time the user clicks a row.
 */
export type PsbtSummary = {
	/**
	 *  Total input value in satoshis (best-effort: only known when the
	 *  previous `witness_utxo`/`non_witness_utxo` is attached).
	 */
	total_input_sats: number | null,
	// Total output value in satoshis.
	total_output_sats: number,
	// Implied fee (`inputs - outputs`) when input totals are known.
	fee_sats: number | null,
	inputs: PsbtInputSummary[],
	outputs: PsbtOutputSummary[],
};

// 1inch v6 quote response, lifted into a stable shape.
export type Quote = {
	// Source token address (lowercase 0x…).
	from_token: string,
	// Destination token address.
	to_token: string,
	// Source amount, base units, decimal string.
	from_amount: string,
	// Estimated destination amount, base units, decimal string.
	to_amount: string,
	// Estimated gas units for the swap (advisory).
	estimated_gas: number,
	// Optional names of protocols routed through.
	protocols: string[],
};

// Output: one row per Sell.
export type RealizedEvent = {
	asset: string,
	ts: number,
	quantity: number,
	proceeds_usd: number,
	cost_basis_usd: number,
	gain_usd: number,
};

export type ReasonCode = "None" | "PerTxCapExceeded" | "DailyCapExceeded";

/**
 *  Snapshot of the recovery-drill reminder state. Frontend uses
 *  this to decide whether to show the "verify your seed" banner.
 */
export type RecoveryDrillStatus = {
	// `true` if a drill is currently due.
	due: boolean,
	// Reminder interval in days. `0` = disabled.
	interval_days: number,
	// Unix seconds of the last completed drill, or `None`.
	last_at: number | null,
};

// Computed risk tier — UI surfaces these as colored badges.
export type RiskLevel = 
// Low-impact (small fixed allowance, well-known spender).
"Low" | 
// Worth reviewing (e.g. moderate allowance, recent first-seen).
"Medium" | 
// Likely needs revocation (unlimited allowance to a single dApp).
"High" | 
// Almost certainly malicious / unknown spender with broad reach.
"Critical";

export type RouteQuotesArgs = {
	// Routing request — see atlas_exchange_router::RoutingRequest.
	request: RoutingRequest,
};

// One routed quote.
export type RoutedQuote = {
	/**
	 *  Provider name (`"oneinch"`, `"jupiter"`, `"thorchain"`,
	 *  `"changenow"`).
	 */
	provider: string,
	/**
	 *  Estimated output amount in display units (decimal string).
	 *  `None` when the provider rejected the quote.
	 */
	out_amount: string | null,
	/**
	 *  Whether this is a same-chain or cross-chain route. Useful
	 *  for the UI to surface "you'll wait ~10 min" warnings on
	 *  cross-chain routes.
	 */
	cross_chain: boolean,
	// Provider error message, when the quote failed.
	error?: string | null,
	/**
	 *  Provider-specific opaque payload; passed back verbatim
	 *  when the user picks this route. Surfaced as a JSON string
	 *  in TS bindings.
	 */
	raw?: string | null,
};

/**
 *  RoutingAsset reference. Atlas-wallet identifies assets by an
 *  `(chain, ticker)` pair plus an optional contract address for
 *  EVM tokens / Solana SPL mints.
 */
export type RoutingAsset = {
	/**
	 *  Chain id in Atlas's internal scheme (e.g. `"bitcoin"`,
	 *  `"ethereum"`, `"solana"`, `"bsc"`). Lowercase ASCII.
	 */
	chain: string,
	/**
	 *  Display ticker, lowercase (e.g. `"btc"`, `"eth"`,
	 *  `"usdc"`).
	 */
	ticker: string,
	/**
	 *  Optional contract / mint address. Only meaningful for
	 *  non-native tokens.
	 */
	contract?: string | null,
	/**
	 *  Decimal precision (display-unit -> base-units multiplier
	 *  is `10^decimals`).
	 */
	decimals: number,
};

/**
 *  Routing request. Amount is given in the *display* unit
 *  (e.g. "0.05" BTC, "10.0" USDC) so the UI doesn't have to
 *  multiply by `10^decimals` four different ways.
 */
export type RoutingRequest = {
	// Source RoutingAsset.
	from: RoutingAsset,
	// Destination RoutingAsset.
	to: RoutingAsset,
	// Source amount as a decimal string in display units.
	amount: string,
	// Slippage tolerance in basis points. Capped per provider.
	slippage_bps: number,
	/**
	 *  User's destination address on the `to.chain`. Required for
	 *  cross-chain providers (THORChain, ChangeNOW); optional for
	 *  same-chain ones (1inch, Jupiter) which embed the user's
	 *  address at swap-tx build time.
	 */
	destination_address?: string | null,
	/**
	 *  Optional Atlas platform-fee configuration. When set, the
	 *  router forwards the matching affiliate / platform-fee
	 *  parameter to each provider.
	 */
	fee?: SwapFee | null,
};

export type RpcEndpoint = {
	chain_id: string,
	// Built-in default URL Atlas falls back to when no override is set.
	default_url: string | null,
	// User-configured override, if any.
	override_url: string | null,
	// The URL providers are actually dialing right now.
	effective_url: string | null,
};

/**
 *  All ten fields the Safe contract hashes for EIP-712. `data` is hex
 *  (`0x...`); everything else is decimal. Addresses are 20-byte hex.
 */
export type SafeTx = {
	// Destination contract / EOA the Safe will call.
	to: string,
	// Wei value to send.
	value: number,
	// Hex-encoded calldata (`0x...`).
	data: string,
	operation: Operation,
	// Gas the Safe forwards to the inner call.
	safe_tx_gas: number,
	// Refund-related gas baseline (typically `0`).
	base_gas: number,
	// Gas price in wei for the refund leg (typically `0`).
	gas_price: number,
	// ERC-20 token used to pay the refund, or `0x000…0` for ETH.
	gas_token: string,
	// Refund receiver, or `0x000…0` for `tx.origin`.
	refund_receiver: string,
	// Safe nonce — must equal `safe.nonce()` at execution time.
	nonce: number,
};

/**
 *  Convenience pair returned to the UI: the canonical `safeTxHash` plus
 *  the `domainSeparator` used to derive it (so the UI can show the user
 *  "this is the chain you think it is").
 */
export type SafeTxHashes = {
	safe_tx_hash: string,
	domain_separator: string,
};

export type SendNativeArgs = {
	chain_id: string,
	to: string,
	amount: string,
	fee_level: string,
};

export type SendNativeResult = {
	txid: string,
	fee: Amount,
};

export type SendTokenArgs = {
	// Token id from the registry (e.g. `usdt-erc20`).
	token_id: string,
	to: string,
	// Token amount in base units (string-encoded u128).
	amount: string,
	fee_level: string,
};

export type SendTokenResult = {
	txid: string,
	// Network fee paid in the chain's native asset.
	fee: Amount,
};

/**
 *  One Shamir share. `x` is the evaluation point (1..=255, never 0)
 *  and `y` is the per-byte polynomial value at `x`.
 */
export type Share = {
	x: number,
	// Hex-encoded ciphertext bytes; same length as the original secret.
	y_hex: string,
};

/**
 *  Coarse risk classification, mirrors `atlas-approvals` but kept
 *  distinct so type names don't collide in the TypeScript bindings.
 */
export type SignatureRisk = "Critical" | "High" | "Medium" | "Low";

/**
 *  How the active profile signs transactions. Used by the Send
 *  flow to decide whether to show the password prompt, the
 *  hardware-device prompt, or refuse outright (watch-only).
 */
export type SigningCapability = 
// No active profile yet.
{ kind: "none" } | 
// Hot wallet — sign in-process after password unlock.
{ kind: "hot" } | 
// Hardware-backed — caller must drive the device.
{ kind: "hardware"; 
// `"ledger"` or `"trezor"`.
vendor: string } | 
// Watch-only — cannot sign at all.
{ kind: "watch_only" };

export type SlippageBand = 
// <= 50 bps (0.50 %).
"Low" | 
// 50 < x <= 200 bps (0.50 % – 2.00 %).
"Normal" | 
// 200 < x <= 1000 bps (2 % – 10 %).
"High" | 
// > 1000 bps (over 10 %): show a confirmation banner.
"Reckless";

// One source's USD (or otherwise consistent unit) price quote.
export type SourceQuote = {
	// Human-readable source name (e.g. `"coingecko"`, `"1inch"`).
	source: string,
	// Quoted price.
	price: number,
};

export type SpendPolicy = {
	// 0 = disabled.
	daily_usd_limit: number,
	// 0 = disabled.
	per_tx_usd_limit: number,
	/**
	 *  If true, exceeding the daily cap blocks the tx; otherwise
	 *  it just requires an extra confirmation.
	 */
	hard_block_on_daily: boolean,
};

export type SpendState = {
	window_started_at: number,
	spent_in_window_usd: number,
};

// Networks where Atlas surfaces native staking.
export type StakingChain = "solana" | "cosmos" | "cardano" | "polkadot" | "ethereum" | "polygon";

/**
 *  Atlas-side fee configuration. Each provider has a different
 *  affiliate mechanism; the wallet stores the union and the
 *  router cherry-picks per provider.
 */
export type SwapFee = {
	/**
	 *  Jupiter platform-fee in basis points (max 50 = 0.5 %).
	 *  Requires a fee_account passed at swap-tx build time.
	 */
	jupiter_platform_fee_bps?: number | null,
	// THORChain affiliate THORName.
	thorchain_affiliate?: string | null,
	// THORChain affiliate basis points (max 1000 = 10 %).
	thorchain_affiliate_bps?: number | null,
};

/**
 *  Atlas-wide swap-fee configuration. Surfaced to the UI so
 *  users can see exactly what cut Atlas takes (currently 0.25 %
 *  by default, capped at 1 %).
 */
export type SwapFeeConfig = {
	// Atlas's default fee in basis points (25 = 0.25 %).
	fee_bps: number,
	// THORChain affiliate THORName, when configured.
	thorchain_affiliate: string | null,
};

export type SwapSettings = {
	slippage_bps: number,
	deadline_secs: number,
};

/**
 *  Subset of the `/swap` response. The `swapTransaction` is a
 *  base-64 encoded Solana versioned transaction the caller signs
 *  and broadcasts itself.
 */
export type SwapTransaction = {
	// Base-64 encoded versioned transaction.
	swapTransaction: string,
	// Last valid blockhash (for retries / expiry).
	lastValidBlockHeight: number,
};

/**
 *  Subset of the `/thorchain/quote/swap` response. THORChain's
 *  schema includes many advisory fields; we keep what the wallet
 *  actually needs to build the deposit transaction.
 */
export type ThorchainQuote = {
	// Address on the source chain to send funds to.
	inbound_address: string,
	// Memo string to attach to the deposit transaction.
	memo: string,
	// Estimated output in 1e8 base units (decimal string).
	expected_amount_out: string,
	// Total fees in destination asset, 1e8 base units.
	total_swap_seconds?: number | null,
	/**
	 *  Block height at which the inbound address rotates.
	 *  THORChain rotates vaults; deposits after this height are
	 *  risky.
	 */
	expiry?: number | null,
	/**
	 *  Suggested gas / fee on the source chain (advisory,
	 *  decimal string in 1e8 base units when present). Surfaced
	 *  as a JSON string in TS bindings since specta can't derive
	 *  on `serde_json::Value`.
	 */
	fees?: string | null,
	// Optional minimum recommended slippage tolerance (bps).
	recommended_min_amount_in?: string | null,
	/**
	 *  Warnings the protocol attaches to the quote (e.g.
	 *  "outbound delay > 24 h"). Surfaced verbatim to the UI.
	 */
	notes?: string | null,
	// Echoed router contract address (EVM only).
	router?: string | null,
};

export type ThorchainQuoteArgs = {
	/**
	 *  Source asset in THORChain notation (e.g. "BTC.BTC",
	 *  "ETH.USDC-0xa0b8...eb48").
	 */
	from_asset: string,
	// Destination asset.
	to_asset: string,
	// Amount in 1e8-fixed-point base units (string-encoded).
	amount: string,
	// Recipient address on the destination chain.
	destination: string,
	// Optional affiliate THORName.
	affiliate: string | null,
	// Optional affiliate basis points (0..=1000).
	affiliate_bps: number | null,
	// Optional minimum acceptable output (slippage protection).
	min_amount_out: string | null,
};

// Token contract standard.
export type TokenStandard = 
// Ethereum / EVM-compatible ERC-20 contract.
"erc20" | 
// Tron TRC-20 contract.
"trc20";

export type TokenSummary = {
	id: string,
	symbol: string,
	display_name: string,
	chain_id: string,
	contract: string,
	decimals: number,
	standard: string,
	enabled_by_default: boolean,
};

// One trade entry.
export type Trade = {
	kind: TradeKind,
	asset: string,
	quantity: number,
	// Price per unit in USD at the time of the trade.
	unit_price_usd: number,
	// Unix seconds.
	ts: number,
};

// What the trade is.
export type TradeKind = "Buy" | "Sell";

// One row in the user's outbound history.
export type TrustedCounterparty = {
	// Address the user previously sent funds to.
	address: string,
	/**
	 *  First time the user sent here (Unix seconds). Used to ensure
	 *  the look-alike arrived *after* the legitimate transfer.
	 */
	first_seen: number,
};

// Display-shape transaction record.
export type Tx = {
	txid: string,
	chain_id: string,
	// `"send"` or `"receive"`.
	direction: string,
	counterparty: string,
	// Decimal-string amount in base units.
	amount: string,
	asset: string,
	// Decimal-string fee in the chain's native asset base units.
	fee: string,
	// Unix seconds.
	timestamp: number,
	// `"pending"`, `"confirmed"`, or `"failed"`.
	status: string,
	memo: string | null,
};

export type TxNote = {
	chain: Chain,
	txid: string,
	note: string,
	tags: string[],
};

// One on-chain transaction the user (or Atlas itself) initiated.
export type TxRecord = {
	// Transaction id / hash, lower-case hex (no `0x` for BTC; with `0x` for EVM).
	txid: string,
	// Chain id (`"btc"`, `"eth"`, `"sol"`, …).
	chain_id: string,
	/**
	 *  `"send"` or `"receive"`. Atlas only writes `"send"` itself today;
	 *  `"receive"` rows are reserved for future explorer-driven enrichment.
	 */
	direction: string,
	// Other party's address.
	counterparty: string,
	// Amount in base units, decimal-string (u128-friendly).
	amount: string,
	// Asset ticker (`"BTC"`, `"ETH"`, `"USDT"`, …).
	asset: string,
	// Network fee paid, decimal string in the chain's native asset base units.
	fee: string,
	// Unix timestamp (seconds) when the tx was broadcast.
	timestamp: number,
	// `"pending"`, `"confirmed"`, or `"failed"`.
	status: string,
	// Optional user-supplied note.
	memo: string | null,
};

/**
 *  Emitted right after a tx is appended to the local cache (whether Atlas
 *  signed it or the UI explicitly recorded an external one). The TX list
 *  view subscribes and updates in place.
 */
export type TxRecordedEvent = {
	record: TxRecord,
};

/**
 *  Emitted when [`crate::commands::tx_history_set_status`] flips a row's
 *  status field (e.g. pending → confirmed once a watcher resolves).
 */
export type TxStatusChangedEvent = {
	chain_id: string,
	txid: string,
	status: string,
};

/**
 *  Result of `user_op_hash` — surfaces the `userOpHash` plus the inner
 *  `packedHash` so a tester can check intermediate values.
 */
export type UserOpHashes = {
	user_op_hash: string,
	packed_hash: string,
};

/**
 *  EntryPoint v0.6 UserOperation. All numeric fields are stored as
 *  `u128` (more than enough — even pre-EIP-1559 max gas prices fit) and
 *  `u64` for nonce.
 */
export type UserOperation = {
	sender: string,
	nonce: number,
	// Hex (`0x...`) — empty (`"0x"`) once the account is already deployed.
	init_code: string,
	// Hex (`0x...`) — the inner call the account executes.
	call_data: string,
	call_gas_limit: number,
	verification_gas_limit: number,
	pre_verification_gas: number,
	max_fee_per_gas: number,
	max_priority_fee_per_gas: number,
	/**
	 *  Hex (`0x...`) — empty (`"0x"`) when there is no paymaster. When
	 *  non-empty, the first 20 bytes are the paymaster contract.
	 */
	paymaster_and_data: string,
};

// One validator the user can delegate to.
export type Validator = {
	chain: StakingChain,
	// Chain-native identifier (vote pubkey, valoper address, pool id, etc).
	id: string,
	name: string,
	// Commission in basis points (10000 = 100%).
	commission_bps: number,
	/**
	 *  Self-reported total stake in the network's base units
	 *  (lamports, uatom, lovelace, plancks, wei). Stored as f64 so
	 *  extreme totals (Polkadot validators) round-trip cleanly through
	 *  JSON without needing u128.
	 */
	total_stake: number,
	/**
	 *  Net APR (after the validator's commission) as a fraction
	 *  (0.045 = 4.5%).
	 */
	net_apr: number,
	/**
	 *  Whether this validator is currently active (in the active set
	 *  / not jailed / not slashed-out).
	 */
	active: boolean,
	/**
	 *  True if Atlas considers this validator decentralisation-friendly
	 *  (small share of total stake, no jail history). Used to bias the
	 *  recommendation list without hiding alternatives.
	 */
	recommended: boolean,
};

/**
 *  Emitted when the wallet transitions from unlocked to locked, regardless
 *  of cause (manual, idle timeout, profile switch, …). The frontend uses
 *  this to evict in-memory state and route to `/unlock`.
 */
export type WalletLockedEvent = {
	// `"manual"`, `"idle"`, `"profile_switch"`, or `"shutdown"`.
	reason: string,
};

// A `(chain_id, address)` pair tracked by a watch-only profile.
export type WatchAccount = {
	// Chain identifier (e.g. `"btc"`, `"eth"`, `"polygon"`).
	chain_id: string,
	// Public address (no private key material).
	address: string,
	// Optional human label.
	label?: string | null,
};

// Parsed `wc:` v2 URI.
export type WcUri = {
	// 32-byte hex topic (the pairing topic).
	topic: string,
	// Relay protocol (typically `"irn"`).
	relay_protocol: string,
	// Optional relay data (forwarded to the relay).
	relay_data: string | null,
	// 32-byte symmetric key, hex-encoded.
	sym_key: string,
	// Optional expiry timestamp (seconds since epoch).
	expiry_timestamp: number | null,
	// Optional methods list as advertised by the dapp.
	methods: string[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

