[package]
name = "atlas-multisig-btc"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = { workspace = true }
miniscript = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
specta = { workspace = true }
hex = { workspace = true }
