[package]
name = "atlas-chain-evm"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "EVM chain provider (Eth + Polygon + BSC + Arbitrum + Optimism + Base)"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
reqwest = { workspace = true }
atlas-net = { workspace = true }
secp256k1 = { workspace = true }
sha3 = { workspace = true }
hex = { workspace = true }
atlas-chain-traits = { workspace = true }

